### ISSUE TITLE
Game crashes.

### ISSUE THREAD

**Issue by KcTec90** [BitCrackers/AmongUsMenu#122]
The game crashes when I put the hack gui offscreen while the Chat is open.
(I'll insert screenshots later.)

**Comment by manianac** [comment]
I have not been able to duplicate this.  Please provide examples of "moving it off screen".  I've drug the window almost entirely out of view without issue.

**Comment by KcTec90** [comment]
oh wait i was using an older version! it probably was an error with visual studio :P

**Comment by KcTec90** [comment]
oh wait i got a screenshot
https://i.gyazo.com/bd8b485283d622456d54c675699ef538.png
