### ISSUE TITLE
Alt tabbing out of game causes keybinds to be set to alt

### ISSUE THREAD

**Issue by 4FK** [BitCrackers/AmongUsMenu#123]
I'm on Windows 10 using the steam version of Among Us and I'm injecting using process hacker. Alt-tabbing out of the game and tabbing back in will bind any keybind you hover over to alt and the only way to fix it is to press alt again and then bind it back to the original key. You have to do this any time you tab out and tab back in again.

Steps to reproduce:
1. Inject
2. Tab out (doesn't matter if menu is closed or open)
3. Hover over any keybind (open menu if you have to)
4. Watch it get set to alt

I;m using the release build. If there is anything else I should add let me know.

**Comment by manianac** [comment]
#124 fixes this.
