### ISSUE TITLE
IMGUI crash when i click

### ISSUE THREAD

**Issue by ABGGamer** [BitCrackers/AmongUsMenu#125]
Hi is there anyone that knows how to fix this
https://gyazo.com/d22ad73ec7e1ec2648fe2e215205ec96

o btw i didnt close the console i minimized it.

thx :)

**Comment by manianac** [comment]
Assuming you're using the paid steam version.  Not cracked, not from any other source.

Make sure you inject on the main menu, NOT already in a match.

Also feel free to try version.dll instead of injecting, the game will auto-load the menu upon startup.

**Comment by ABGGamer** [comment]
i am using paid verson and i also tried to inject it in the menu and i also tried version.dll in debug and release mode :/

**Comment by manianac** [comment]
@ABGGamer Can you try a fresh build off of Discord?  Try with placing verison.dll in the game folder and starting the game.

**Comment by manianac** [comment]
Closing, never duplicated.
