### ISSUE TITLE
Radar Lost - Doesn't Show Up | Also How To reset Settings To Brand New?

### ISSUE THREAD

**Issue by JonasBoy77** [BitCrackers/AmongUsMenu#128]
I think I accidently dragged the Radar off-screen so far that I can't drag it back on:
![image](https://user-images.githubusercontent.com/79479070/108763540-583fb580-75b6-11eb-8ab1-daf3ece1def3.png)

Is there any way I can reset the Menu setting's to default?

Thanks.

**Comment by v0idp** [comment]
delete imgui config file in game folder
