### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by KcTec90** [BitCrackers/AmongUsMenu#129]
https://github.com/BitCrackers/AmongUsMenu/issues/122
![bd8b485283d622456d54c675699ef538](https://user-images.githubusercontent.com/74018250/109338549-46128100-781b-11eb-8a7c-789538ebd913.png)
See.

**Comment by OsOmE1** [comment]
We were not able to replicate this issue as @manianac stated before please do not make another issue.
