### ISSUE TITLE
Radar maps are vertically mirrored

### ISSUE THREAD

**Issue by Ten0** [BitCrackers/AmongUsMenu#130]
I'm getting radar maps vertically mirrored on Polus and Mira (not sure about Skeld yet), which makes it hard to visualize.

**Comment by OsOmE1** [comment]
Try and delete your settings file and provide more info if that doesn't work

**Comment by Ten0** [comment]
So I freshly installed it yesterday, so I started with an empty config file.
More info:
 - I freshly installed `Visual Studio` C++ for Windows
 - Used the internal tool to clone the repository -> It asked me whether I wanted to update the `PlatformToolset` of the project from v141 to v142 because I already had the latest installed. I said *yes*.
 - I attempted to compile -> It told me I needed a library and to install it through the Visual Studio Installer (I don't remember the name but I remember it was a 3 letter name). I did install the version that was dedicated to "v142 x86/x64".
 - I compiled, injected the DLL using Cheat Engine 7.2, (by the way, file gets removed as soon as I inject it, and I have the same issue with the "version proxy", except it gets removed without actually even getting injected. Injecting with Cheat Engine 6.7 resulted in dll being removed and injection failure as well.)
 - Created a game, pressed "Insert" to get the radar -> map is mirrored vertically.

**Comment by OsOmE1** [comment]
Make sure to read the readme. Version dll is supposed to be in the games root directory and is not supposed to be injected. It will automatically be loaded at startup.

**Comment by Ten0** [comment]
> Make sure to read the readme. Version dll is supposed to be in the games root directory and is not supposed to be injected. It will automatically be loaded at startup.

This seems unrelated to the other issue, but that's what I did. To make it more clear (maybe) than my previous message
 - Injecting Normal with CheatEngine 7.2 injects successfully, but dll gets deleted
 - Injecting Normal with CheatEngine 6.7 fails to inject, and dll gets deleted
 - Putting version dell in game directory and starting the game, menu is not loaded and dll gets deleted.

**Comment by OsOmE1** [comment]
Your dll might be getting deleted by windows defender you might want to check that out first because it should be deleted. Also try a different injector like GH Injector come join the discord server easier support.

**Comment by Ten0** [comment]
Looking a bit at the code, I suspect that might be related to this?
https://github.com/BitCrackers/AmongUsMenu/blob/364b4594cab2c2d89a5e55717e5fe53f6c0077f4/gui/radar.cpp#L79-L84

**Comment by Ten0** [comment]
missclick*

**Comment by OsOmE1** [comment]
That code flips the map horizontally in case of flipped skeld

**Comment by OsOmE1** [comment]
The weird thing is I've had this issue before, but I can't remember how I solved it.

**Comment by Ten0** [comment]
Ok so I found the solution.
As it turns out, my antivirus was silently removing the DLLs as you suggested, and adding it to the exclude list solved both issues at once! The maps are not flipped anymore!

That's a very weird behaviour, but anyway, fixed!
