### ISSUE TITLE
The Mod Menu Crashes the Game if You Hit an Undefined (or Disabled) Key on Your Keyboard.

### ISSUE THREAD

**Issue by Bj007pro** [BitCrackers/AmongUsMenu#136]
So, I am the type of keyboard user that doesn't like to use the Caps Lock key and use the Shift key to uppercase my letters.
I've disabled my Caps Lock key because, one I don't use it, but for the main reason I fat-figure hitting it while playing a game and when typing.

**Comment by manianac** [comment]
How did you disable it?

**Comment by Bj007pro** [comment]
> How did you disable it?

I used another open source project here on GitHub called SharpKeys developed by RandyRants that edits the registry for you;
https://github.com/randyrants/sharpkeys
