### ISSUE TITLE
[Update 18/03/2021] Doors Tab Has a Chance of Showing On Polus

### ISSUE THREAD

**Issue by Bj007pro** [BitCrackers/AmongUsMenu#137]
[Update 18/03/2021]

As Imposter or Crewmate the Doors tab has a chance of not showing:
![image](https://user-images.githubusercontent.com/24400879/111365335-3f2eae00-86f7-11eb-8011-ff722c1e2a79.png)

And if it does show, clicking on the tab with crash the game.

**Comment by manianac** [comment]
It would seem that ShipStatus_OnEnable is not called here.  I will look into this
