### ISSUE TITLE
Broken radar in new update

### ISSUE THREAD

**Issue by doggobot-owner** [BitCrackers/AmongUsMenu#151]
The radar in the new update is broken. Its kinda reversed, randomized and moved a little bit down (skeld) didnt test other maps

**Comment by Cyber-Crud** [comment]
Odd, I do not have any map issues at all.  Try deleting the old settings.json file where the version.dll lives and see if it makes a difference.

**Comment by OsOmE1** [comment]
Yeah, delete your settings.json
