### ISSUE TITLE
Building for windows 7

### ISSUE THREAD

**Issue by johnnycash133** [BitCrackers/AmongUsMenu#152]
I've built fine for windows 10 and it was no issue, I change the <WindowsTargetPlatformVersion>7</WindowsTargetPlatformVersion> changed it windows seven, now when I am building it

http://prntscr.com/10uqozi

I get this error compiling/building

http://prntscr.com/10uqrc2

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'math.h': No such file or directory	AmongUsMenu	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\include\cstdlib	12

**Comment by Cyber-Crud** [comment]
I don't think the hack will work on Windows 7 for DirectX compatibility reasons. I have not been able to get it to work on Windows 7 at all.

**Comment by OsOmE1** [comment]
Yeah exactly, we won't support any other version of windows except 10. If you want to compile it you'll have to do it yourself.
