### ISSUE TITLE
Issues with v2021.3.31s (Airship release)

### ISSUE THREAD

**Issue by Cyber-Crud** [BitCrackers/AmongUsMenu#159]
I compiled the 4/1 repository and the crashing from the previous versions are gone.  However, there are a few weird issues:

1.  The max vision thru walls doesn't seem to work.  I have tried it on a couple of maps to no avail.  I still see the shadows.
2.  My game gets stuck sometimes after the first meeting.  The game plays but I cannot move, nor can some other players.  If I am imp, even my cooldown does not count down.  I can still teleport though, but I cannot move.  At some point it releases.
3.  I dunno if this is a game but or a hack bug, but the splash screen for emergency meetings or reports do not appear.  If I report, it goes straight to meeting without a transition.  
4.  The cheat console option still erroneously detects some players as teleporting, when they are not. 

I also get a crash on first launch, but the game and cheat still runs anyway, which is very odd.  

Here are the warnings received during the build with v141:

D:\VS2019\AmongUsMenu-2021.3.31s\hooks\DirectX.cpp(176,7): warning C4834: discarding return value of function with 'nodiscard' attribute
D:\VS2019\AmongUsMenu-2021.3.31s\hooks\InnerNetClient.cpp(111,30): warning C4244: 'initializing': conversion from 'float' to 'int32_t', possible loss of data
D:\VS2019\AmongUsMenu-2021.3.31s\user\utility.cpp(484,5): warning C4305: 'initializing': truncation from 'double' to 'float'
D:\VS2019\AmongUsMenu-2021.3.31s\user\utility.cpp(487,5): warning C4305: 'initializing': truncation from 'double' to 'float'

**Comment by Ten0** [comment]
Additionally:
 - Emptying the name change textbox gets you instabanned for hacking (server does not tolerate empty names).

**Comment by Cyber-Crud** [comment]
Have you tried nul ascii characters?

**Comment by OsOmE1** [comment]
All of these changes should now be fixed
Except for nr. 2 which is an innersloth bug
