### ISSUE TITLE
Main branch - 4/5/21 Release Crash on Imp Win

### ISSUE THREAD

**Issue by Cyber-Crud** [BitCrackers/AmongUsMenu#168]
Gentlemen, I compiled the April 5th update this morning and noticed that everything had worked perfectly.  It does have the launch crash, but this is a known issue -- doesn't seem to affect the game play though.  And the 2nd round being stuck is also present, but if that is an Innersloth issue, that is fine.  Clicking the settings cog fixes it immediately.  

However, I have found that if I am Impostor (and not host) the game will sometimes crash instead of giving me a victory screen.  I have not been able to duplicate this as host imp, but it happens quite often as guest imp.   It's the only consistent crash I am getting in this release.  Every other option works like a charm!  All previous opened issues of mine are resolved. 

Faulting application name: Among Us.exe, version: 2020.2.6.8515, time stamp: 0x602f2479
Faulting module name: VERSION.dll, version: 0.0.0.0, time stamp: 0x606b4188
Exception code: 0xc0000005
Fault offset: 0x002ad148
Faulting process id: 0x1064
Faulting application start time: 0x01d72a4b5ddce619
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\Among Us\Among Us.exe
Faulting module path: C:\Program Files (x86)\Steam\steamapps\common\Among Us\VERSION.dll
Report Id: 31b11182-a147-4198-ac4f-9a2dcaaad134
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket 1175264411417684336, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Among Us.exe
P2: 2020.2.6.8515
P3: 602f2479
P4: VERSION.dll
P5: 0.0.0.0
P6: 606b4188
P7: c0000005
P8: 002ad148
P9: 
P10:

**Comment by OsOmE1** [comment]
@Cyber-Crud we generate logs now can you attach that its called aum-log.txt and it should be in your among us root directory

**Comment by Cyber-Crud** [comment]
[aum-log.txt](https://github.com/BitCrackers/AmongUsMenu/files/6260488/aum-log.txt)

Perfect.  I cleared that file and just had a crash on a game win as crew.  Imp quit, we won the game.  On victory screen, game crashed.  This was the first crash I had that was not due to me being the imp.

**Comment by OsOmE1** [comment]
Right not much there as I suspected.
If you know how to build using visual studio and attach a debugger please do so. Otherwise I will try to recreate the error myself tomorrow.

**Comment by Cyber-Crud** [comment]
Strangely enough, I turned off Windows Error Reporting and I have not had
another crash.  I will test that more tomorrow to see if that is a fluke.
