### ISSUE TITLE
Banned message when injecting latest aum

### ISSUE THREAD

**Issue by bdl555** [BitCrackers/AmongUsMenu#169]
I downloaded the latest main branch and compiled it in visual studio. Now whenever I inject the menu I get the "You were banned for hacking. please stop" even if I inject it on the main menu. Whenever I join a lobby after I get kicked immediately and get the same message.

**Comment by manianac** [comment]
What is your player name?

**Comment by bdl555** [comment]
hidenseek usually

**Comment by bdl555** [comment]
Oddly enough I tried it now and it seems to be working fine now.
