### ISSUE TITLE
Modded Among Us - constant crashing in online games

### ISSUE THREAD

**Issue by N-Impostor** [BitCrackers/AmongUsMenu#170]
Latest Steam version (v2021.3.31.3s), latest AUM version (#166) (tried version and version_debug). Specific mod that I'm using - https://github.com/AJMix/TownOfImpostors

Game constantly crashes within seconds of starting an online game, regardless of whether I'm host or not, and seemingly not based on my actions - most often I manage to run for up to 5 seconds before the crash occurs. So far I only had the chance to try out the new map (The Airship).

Playing in freeplay produces no crashes regardless of the map.

Debug logs:  [aum-log-debug.txt](https://github.com/BitCrackers/AmongUsMenu/files/6266110/aum-log-debug.txt)
Non-debug version logs: [aum-log-non-debug.txt](https://github.com/BitCrackers/AmongUsMenu/files/6266113/aum-log-non-debug.txt)

**Comment by manianac** [comment]
Mods are unsupported at this time and will result in a crash
