### ISSUE TITLE
MSB3073

### ISSUE THREAD

**Issue by VVVANNONVVVV** [BitCrackers/AmongUsMenu#174]
Hello.
I've got error because of wrong file path while compiling I guess but dunno where to change it.
 Create gitparams.h
  fatal: not a git repository (or any of the parent directories): .git
  fatal: not a git repository (or any of the parent directories): .git
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(139,5): error MSB3073: Command„echo | set /p dummyName=#define GIT_CUR_COMMIT >  user/gitparams.h
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(139,5): error MSB3073: git rev-parse --verify HEAD >>  user/gitparams.h
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(139,5): error MSB3073: 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(139,5): error MSB3073: echo | set /p dummyName=#define GIT_BRANCH >>  user/gitparams.h
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(139,5): error MSB3073: git rev-parse --abbrev-ref HEAD >>  user/gitparams.h
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(139,5): error MSB3073: :VCEnd” has been finished by code 128.

**Comment by its-pablo** [comment]
Wait did you fix it tho?
