### ISSUE TITLE
Among Us Crashes in latest version

### ISSUE THREAD

**Issue by Xtendera** [BitCrackers/AmongUsMenu#200]
I just updated Among Us from the Epic Games store. When I join a game and it starts, the app crashes even if the menu is not open. Without the menu, it works just fine. I don't know if this is only my issue or a universal issue, but any help would be fantastic.

Thank you for this amazing app!

----

DEBUG INFO:
Among Us Source: Epic Games Store
Among Us Version: 2021.6.15
Operating System: Windows 21H1
Inject Method: version.dll

**Comment by ChaseBrand** [comment]
@manianac pre-released a version earlier today that should work on the latest version. If you haven't updated the menu yet, that's the best place to start.

If you're in our discord you can run /builds and click on the "Latest Absolute Release" to find the pre-release I'm talking about at the top.

**Comment by Xtendera** [comment]
Thank you so much!!
