### ISSUE TITLE
[FEAT] Custom font in ImGui

### ISSUE THREAD

**Issue by 4310V343k** [BitCrackers/AmongUsMenu#203]
All non-Latin characters are displayed as `?`.
[FAQ on Dear ImGui GH on fixing this](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-display-and-input-non-latin-characters-such-as-chinese-japanese-korean-cyrillic)
[More Info](https://github.com/ocornut/imgui/blob/master/docs/FONTS.md)

**Comment by MP3Martin** [comment]
true

**Comment by v0idp** [comment]
Are there any characters we should look out for which cause this ``?`` to be shown in AUM ? Because I didn't see anything like that yet except maybe for some Usernames maybe which is really rare.

**Comment by manianac** [comment]
Yea Japanese/Russian usernames are the only ones I have seen

**Comment by 4310V343k** [comment]
I can paste russian alphabet if that can help

**Comment by manianac** [comment]
Naw, someone just needs to make a PR using a new font would likely do it

**Comment by v0idp** [comment]
can you provide any screenshots with an example ?

**Comment by 4310V343k** [comment]
> can you provide any screenshots with an example ?

[This](https://i.imgur.com/PtYd7Jf.png) is what happens without russian glyphs

**Comment by v0idp** [comment]
Thanks we will look into this soon
