### ISSUE TITLE
among us unity keeps popping up and game crashes

### ISSUE THREAD

**Issue by ShurikenTY** [BitCrackers/AmongUsMenu#215]
my game keeps crashing whenever i try to use the radar

**Comment by v0idp** [comment]
Can you try the debug build and try the radar again. If it crashes post the debug logs here.

**Comment by 4310V343k** [comment]
![](https://i.imgur.com/720a8ok.png)

**Comment by ChaseBrand** [comment]
We'll need you to post your debug logs. They can be found in the game's folder.

**Comment by ChaseBrand** [comment]
Marking this as stale and closing the Issue.
