### ISSUE TITLE
Weird error found in 2021.6.30s

### ISSUE THREAD

**Issue by StupidRepo** [BitCrackers/AmongUsMenu#216]
<img width="329" alt="image" src="https://user-images.githubusercontent.com/69256931/127856277-63df92b9-5e7d-4442-90bd-59cc523d2b6c.png">
Help please

**Comment by StupidRepo** [comment]
Ok somehow I averted the error (Installed NET framework) but the game crashes. This happens when cheats are outdating so I am looking forward to the 2021.6.30s version of this cheat

**Comment by StupidRepo** [comment]
Nevermind the error is back in the debug mode

**Comment by StupidRepo** [comment]
OK the error is fully back, RIP. @manianac please get onto this

**Comment by StupidRepo** [comment]
@manianac#5797

**Comment by v0idp** [comment]
there is no need to spam this thread. Please provide the debug logs from the game folder and let me know what you did before the moment it crashed with that error up there

**Comment by StupidRepo** [comment]
I was using crossover 20 on an M1 Mac to use this mod, turns out using it on an ACTUAL x64 windows 10 PC fixed it. Sad that the PC I am using is crap though.
