### ISSUE TITLE
Among us Crashes when trying to join a new lobby

### ISSUE THREAD

**Issue by FeyrisTan** [BitCrackers/AmongUsMenu#217]
Exactly what the title says. The error message appearing on screen is:
SVR_STRMISS

Using debug build.
Dont know if the log is actually the aum-log.txt but thats all I found so:

[DEBUG - AUM - GetCRC32] CRC32 of "C:\Program Files (x86)\Steam\steamapps\common\Among Us\GameAssembly.dll" is ea2527f3
[INFO - AUM - Run] 
	AmongUsMenu - Jul  8 2021 - 23:17:02
	Build: Debug_Version
	Commit: 240d4d31046771dce91e491f21aa0a5f735b9a23 - HEAD
	Among Us Version: 2021.6.30

[DEBUG - AUM - cctor_finished] Class AmongUsClient Has Static Constructor: false
[DEBUG - AUM - Run] Game::pAmongUsClient is 0x09ED29D8 -> 0x00000000
[DEBUG - AUM - cctor_finished] Class GameData Has Static Constructor: true
[DEBUG - AUM - Run] Game::pGameData is 0x09ED2B90 -> 0x00000000
[DEBUG - AUM - cctor_finished] Class PlayerControl Has Static Constructor: true
[DEBUG - AUM - Run] Game::pGameOptionsData is 0x09ED4D94 -> 0x1A71CD20
[DEBUG - AUM - cctor_finished] Class PlayerControl Has Static Constructor: true
[DEBUG - AUM - Run] Game::pAllPlayerControls is 0x09ED4D98 -> 0x1A72BCC0
[DEBUG - AUM - cctor_finished] Class PlayerControl Has Static Constructor: true
[DEBUG - AUM - Run] Game::pLocalPlayer is 0x09ED4D90 -> 0x00000000
[DEBUG - AUM - cctor_finished] Class ShipStatus Has Static Constructor: false
[DEBUG - AUM - Run] Game::pShipStatus is 0x1D609A88 -> 0x00000000
[DEBUG - AUM - cctor_finished] Class LobbyBehaviour Has Static Constructor: false
[DEBUG - AUM - Run] Game::pLobbyBehaviour is 0x09ED2B30 -> 0x00000000
[DEBUG - AUM - cctor_finished] Class SaveManager Has Static Constructor: true
[ERROR - UNITY] DeviceId access credentials already exist for the current user profile on the local device.
[DEBUG - AUM - dPresent] ImGui Initialized successfully!
[DEBUG - AUM - dPresent] Fullscreen: 1
[DEBUG - AUM - dPresent] Unity Window Resolution: 1920x1080
[DEBUG - AUM - dPresent] DirectX Window Size: 1920x1080
[DEBUG - UNITY] Auth with Steam
[DEBUG - UNITY] [154 - EncryptedAppTicketResponse] - k_EResultOK
[DEBUG - UNITY] Menu: Loading => CloseOverlayMenu()
[INFO - UNITY] Attempting to close: Loading, but menu was never opened.
[DEBUG - UNITY] Menu: BackgroundFill => CloseOverlayMenu()
[INFO - UNITY] Attempting to close: BackgroundFill, but menu was never opened.
[DEBUG - UNITY] country DE
[DEBUG - UNITY] consent 16
[INFO - UNITY] Failed to highlight, selection is null
[DEBUG - UNITY] Set current state to topmost menu BackgroundFill
[DEBUG - UNITY] Login with Steam
[DEBUG - UNITY] login is success
[INFO - UNITY] Error response received from backend. ServiceName=[KWS], OperationName=[GetPermissions], Url=[<Redacted>], HttpStatus=[404], ErrorCode=[error.com.epicgames.identity.kws.integration.user_not_found], NumericErrorCode=[210002], ErrorMessage=[User with id 0001323ad8a142e681de21e552d425cf does not exist.], CorrId=[EOS-qZzpbvV1A06rDWVDNSYl4Q-KJpqWJRN40uH3hIfMEt_aQ-F6vM0hzShkarhMDzk3Rb8A]
[DEBUG - UNITY] Menu: BackgroundFill => CloseOverlayMenu()
[DEBUG - UNITY] Set current state to topmost menu MainMenuManager
[DEBUG - UNITY] is adult
[DEBUG - UNITY] were logged in
[DEBUG - UNITY] finishing flow, login status LoggedIn
[DEBUG - UNITY] *******************updating to LOGGED IN MODE
[DEBUG - UNITY] Requesting announcement from: 172.105.249.25
[DEBUG - UNITY] SaveAnnouncements
[DEBUG - UNITY] SceneChanger::ChangeScene to: MMOnline
[DEBUG - UNITY] Menu: ControllerDisconnectScreen => CloseOverlayMenu()
[INFO - UNITY] Attempting to close: ControllerDisconnectScreen, but menu was never opened.
[INFO - UNITY] Attempting to add variant for QCAccAKilledB with an empty string
[INFO - UNITY] Duplicate translation for QCAccAKilledB: '{0} killed {1}' and '{0} killed {1}'
[INFO - UNITY] Duplicate translation for QCAccAKilledBNeg: '{0} didn't kill {1}' and '{0} didn't kill {1}'
[INFO - UNITY] Duplicate translation for QCAccAIsSuspicious: '{0} is suspicious' and '{0} is suspicious'
[INFO - UNITY] Duplicate translation for QCAccAIsSuspiciousNeg: '{0} is good' and '{0} is good'
[INFO - UNITY] Duplicate translation for QCAccASawBVent: '{0} saw {1} vent' and '{0} saw {1} vent'
[INFO - UNITY] Duplicate translation for QCAccASawBVentNeg: '{0} never saw {1} vent' and '{0} never saw {1} vent'
[INFO - UNITY] Duplicate translation for QCAccAWasChasingB: '{0} was chasing {1}' and '{0} was chasing {1}'
[INFO - UNITY] Duplicate translation for QCAccAWasChasingBNeg: '{0} wasn't chasing {1}' and '{0} wasn't chasing {1}'
[INFO - UNITY] Duplicate translation for QCAccAIsLying: '{0} is lying' and '{0} is lying'
[INFO - UNITY] Duplicate translation for QCAccAIsLyingNeg: '{0} is telling the truth' and '{0} is telling the truth'
[INFO - UNITY] Duplicate translation for QCAccVoteA: 'vote {0}' and 'vote {0}'
[INFO - UNITY] Duplicate translation for QCAccVoteANeg: 'don't vote {0}' and 'don't vote {0}'
[INFO - UNITY] Duplicate translation for QCAccADidntReport: '{0} didn't report the body' and '{0} didn't report the body'
[INFO - UNITY] Duplicate translation for QCResAWas: '{0} was' and '{0} was'
[INFO - UNITY] Duplicate translation for QCResAWasNeg: '{0} wasn't' and '{0} wasn't'
[INFO - UNITY] Duplicate translation for QCResADid: '{0} did' and '{0} did'
[INFO - UNITY] Duplicate translation for QCResADidNeg: '{0} didn't' and '{0} didn't'
[INFO - UNITY] Duplicate translation for QCResAWasAtB: '{0} was at {1}' and '{0} was at {1}'
[INFO - UNITY] Duplicate translation for QCResAWasAtBNeg: '{0} wasn't at {1}' and '{0} wasn't at {1}'
[INFO - UNITY] Duplicate translation for QCQstWhoWasWith: 'who was with {0}?' and 'who was with {0}?'
[INFO - UNITY] Duplicate translation for QCQstWhatWasADoing: 'what was {0} doing?' and 'what was {0} doing?'
[INFO - UNITY] Duplicate translation for QCQstWhereWasA: 'where was {0}?' and 'where was {0}?'
[INFO - UNITY] Duplicate translation for QCStaASawB: '{0} saw {1}' and '{0} saw {1}'
[INFO - UNITY] Duplicate translation for QCStaAWasWithB: '{0} was with {1}' and '{0} was with {1}'
[INFO - UNITY] Duplicate translation for QCStaADidB: '{0} did {1}' and '{0} did {1}'
[INFO - UNITY] Duplicate translation for QCStaASelfReported: '{0} self reported' and '{0} self reported'
[INFO - UNITY] Duplicate translation for QCStaACalledMeeting: '{0} called a meeting' and '{0} called a meeting'
[INFO - UNITY] Duplicate translation for EngagementScreen: 'Press any button to start.' and 'Press any button to start.'
[INFO - UNITY] Duplicate translation for SaveGameOutOfSpaceConfirm: 'Continue' and 'Continue'
[INFO - UNITY] No Translation for DataPolicyTitle (193) in language: English
[INFO - UNITY] No Translation for DataPolicyText (194) in language: English
[INFO - UNITY] No Translation for VitalsOK (341) in language: English
[INFO - UNITY] No Translation for VitalsDEAD (342) in language: English
[INFO - UNITY] No Translation for VitalsDC (343) in language: English
[INFO - UNITY] No Translation for NoTranslation (1003) in language: English
[INFO - UNITY] No Translation for ANY (2061) in language: English
[INFO - UNITY] No Translation for CreateTryAgain (2125) in language: English
[INFO - UNITY] No Translation for ColorSunset (2148) in language: English
[INFO - UNITY] No Translation for DownloadLabel (2167) in language: English
[INFO - UNITY] No Translation for UploadLabel (2168) in language: English
[INFO - UNITY] No Translation for HolidayHatLabel (2186) in language: English
[DEBUG - UNITY] ResetAll()
[DEBUG - UNITY] Among Us Version v2021.6.30s Pipeline Build Num: 967
[INFO - UNITY] Failed to highlight, selection is null
[DEBUG - UNITY] Set current state to topmost menu MMOnlineManager
[ERROR - UNITY] Dropping ApplicationData record. Cannot process yet
[DEBUG - UNITY] Menu: ControllerDisconnectScreen => CloseOverlayMenu()
[INFO - UNITY] Attempting to close: ControllerDisconnectScreen, but menu was never opened.
[DEBUG - UNITY] ResetAll()
[DEBUG - UNITY] Changed To FindAGame
[INFO - UNITY] Failed to highlight, selection is null
[DEBUG - UNITY] Set current state to topmost menu FindAGameManager
[DEBUG - UNITY] Among Us Version v2021.6.30s Pipeline Build Num: 967
[DEBUG - UNITY] Connecting to: 185.19.216.35 for UIGGIF
[DEBUG - UNITY] Client DC because NewConnection: null
[DEBUG - UNITY] Client joining game: -1933946294/UIGGIF
[DEBUG - UNITY] Alter Public = True
[DEBUG - UNITY] Menu: WaitingForHostPopup => CloseOverlayMenu()
[INFO - UNITY] Attempting to close: WaitingForHostPopup, but menu was never opened.
[DEBUG - UNITY] ResetAll()
[DEBUG - UNITY] Changed To OnlineGame
[DEBUG - UNITY] Self changed scene: 34862 OnlineGame
[INFO - UNITY] Stored Msg 0 RPC SetStartCounter for 19
[INFO - UNITY] Stored Msg 1 RPC SetStartCounter for 10
[INFO - UNITY] Stored Msg 2 RPC SetStartCounter for 13
[INFO - UNITY] Stored Msg 3 RPC SetStartCounter for 3
[INFO - UNITY] Stored data for 33
[INFO - UNITY] Stored Msg 5 RPC SetPet for 31
[INFO - UNITY] Stored Msg 6 RPC SetHat for 31
[INFO - UNITY] Stored Msg 7 RPC SetSkin for 31
[INFO - UNITY] Stored data for 24
[INFO - UNITY] Stored Msg 9 RPC SetStartCounter for 22
[DEBUG - UNITY] Graphics API has geometry shader support
[DEBUG - UNITY] Client DC because Custom: SVR_STRMISS
[INFO - UNITY] Failed to highlight, selection is null
[DEBUG - UNITY] Set current state to topmost menu DisconnectPopup
[DEBUG - UNITY] Menu: WaitingForHostPopup => CloseOverlayMenu()
[INFO - UNITY] Attempting to close: WaitingForHostPopup, but menu was never opened.
[INFO - UNITY] Attempting to add variant for QCAccAKilledB with an empty string
[INFO - UNITY] Duplicate translation for QCAccAKilledB: '{0} killed {1}' and '{0} killed {1}'
[INFO - UNITY] Duplicate translation for QCAccAKilledBNeg: '{0} didn't kill {1}' and '{0} didn't kill {1}'
[INFO - UNITY] Duplicate translation for QCAccAIsSuspicious: '{0} is suspicious' and '{0} is suspicious'
[INFO - UNITY] Duplicate translation for QCAccAIsSuspiciousNeg: '{0} is good' and '{0} is good'
[INFO - UNITY] Duplicate translation for QCAccASawBVent: '{0} saw {1} vent' and '{0} saw {1} vent'
[INFO - UNITY] Duplicate translation for QCAccASawBVentNeg: '{0} never saw {1} vent' and '{0} never saw {1} vent'
[INFO - UNITY] Duplicate translation for QCAccAWasChasingB: '{0} was chasing {1}' and '{0} was chasing {1}'
[INFO - UNITY] Duplicate translation for QCAccAWasChasingBNeg: '{0} wasn't chasing {1}' and '{0} wasn't chasing {1}'
[INFO - UNITY] Duplicate translation for QCAccAIsLying: '{0} is lying' and '{0} is lying'
[INFO - UNITY] Duplicate translation for QCAccAIsLyingNeg: '{0} is telling the truth' and '{0} is telling the truth'
[INFO - UNITY] Duplicate translation for QCAccVoteA: 'vote {0}' and 'vote {0}'
[INFO - UNITY] Duplicate translation for QCAccVoteANeg: 'don't vote {0}' and 'don't vote {0}'
[INFO - UNITY] Duplicate translation for QCAccADidntReport: '{0} didn't report the body' and '{0} didn't report the body'
[INFO - UNITY] Duplicate translation for QCResAWas: '{0} was' and '{0} was'
[INFO - UNITY] Duplicate translation for QCResAWasNeg: '{0} wasn't' and '{0} wasn't'
[INFO - UNITY] Duplicate translation for QCResADid: '{0} did' and '{0} did'
[INFO - UNITY] Duplicate translation for QCResADidNeg: '{0} didn't' and '{0} didn't'
[INFO - UNITY] Duplicate translation for QCResAWasAtB: '{0} was at {1}' and '{0} was at {1}'
[INFO - UNITY] Duplicate translation for QCResAWasAtBNeg: '{0} wasn't at {1}' and '{0} wasn't at {1}'
[INFO - UNITY] Duplicate translation for QCQstWhoWasWith: 'who was with {0}?' and 'who was with {0}?'
[INFO - UNITY] Duplicate translation for QCQstWhatWasADoing: 'what was {0} doing?' and 'what was {0} doing?'
[INFO - UNITY] Duplicate translation for QCQstWhereWasA: 'where was {0}?' and 'where was {0}?'
[INFO - UNITY] Duplicate translation for QCStaASawB: '{0} saw {1}' and '{0} saw {1}'
[INFO - UNITY] Duplicate translation for QCStaAWasWithB: '{0} was with {1}' and '{0} was with {1}'
[INFO - UNITY] Duplicate translation for QCStaADidB: '{0} did {1}' and '{0} did {1}'
[INFO - UNITY] Duplicate translation for QCStaASelfReported: '{0} self reported' and '{0} self reported'
[INFO - UNITY] Duplicate translation for QCStaACalledMeeting: '{0} called a meeting' and '{0} called a meeting'
[INFO - UNITY] Duplicate translation for EngagementScreen: 'Press any button to start.' and 'Press any button to start.'
[INFO - UNITY] Duplicate translation for SaveGameOutOfSpaceConfirm: 'Continue' and 'Continue'
[INFO - UNITY] No Translation for DataPolicyTitle (193) in language: English
[INFO - UNITY] No Translation for DataPolicyText (194) in language: English
[INFO - UNITY] No Translation for VitalsOK (341) in language: English
[INFO - UNITY] No Translation for VitalsDEAD (342) in language: English
[INFO - UNITY] No Translation for VitalsDC (343) in language: English
[INFO - UNITY] No Translation for NoTranslation (1003) in language: English
[INFO - UNITY] No Translation for ANY (2061) in language: English
[INFO - UNITY] No Translation for CreateTryAgain (2125) in language: English
[INFO - UNITY] No Translation for ColorSunset (2148) in language: English
[INFO - UNITY] No Translation for DownloadLabel (2167) in language: English
[INFO - UNITY] No Translation for UploadLabel (2168) in language: English
[INFO - UNITY] No Translation for HolidayHatLabel (2186) in language: English
[DEBUG - UNITY] ResetAll()
[DEBUG - UNITY] Among Us Version v2021.6.30s Pipeline Build Num: 967
[INFO - UNITY] DisconnectPopup menu found, restore after new scene.
[INFO - UNITY] Failed to highlight, selection is null
[DEBUG - UNITY] Set current state to topmost menu MMOnlineManager
[INFO - UNITY] Failed to highlight, selection is null
[DEBUG - UNITY] Set current state to topmost menu DisconnectPopup

**Comment by ChaseBrand** [comment]
Marking this as stale and closing the Issue.
