### ISSUE TITLE
keybinds and random name

### ISSUE THREAD

**Issue by trevorguo-dev** [BitCrackers/AmongUsMenu#221]
i want more keybinds, like a menu that allows you to set a menu for each door closing or each thing you can sabotage, as well as stop spectating. also, i want a button that will give me a random name that is a string of 2 random words, and quick change color, or maybe both in the same button. thanks for your hard work!!

**Comment by v0idp** [comment]
we don't take feature requests like this here. if you're interested into this project you can always make a pull request with your changes and we will look at it. thanks!
