### ISSUE TITLE
Trojan Zpevdo.B

### ISSUE THREAD

**Issue by VVVANNONVVVV** [BitCrackers/AmongUsMenu#225]
Today, they decided to make online updates to your computers with Zpevdo.B trojan.

**Comment by ChaseBrand** [comment]
You look like a fool. This is an open source project and you won't get any more attention for trolling with posts like these. Read the code, understand the code, and don't download anything you don't trust.

We haven't uploaded or made any online connections to any kind of malware whatsoever. There wasn't even a commit to this project today.

**Comment by v0idp** [comment]
also the release always reflects the actual source code since it's being build automatically in github actions from the source code.
