### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by Mr-Legendary-Pineapple** [BitCrackers/AmongUsMenu#226]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "echo | set /p dummyName=#define GIT_CUR_COMMIT >  user/gitparams.h
git rev-parse --verify HEAD >>  user/gitparams.h

echo | set /p dummyName=#define GIT_BRANCH >>  user/gitparams.h
git rev-parse --abbrev-ref HEAD >>  user/gitparams.h
:VCEnd" exited with code 128.	AmongUsMenu	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	145

**Comment by ChaseBrand** [comment]
You need to [install Git](https://git-scm.com/).

**Comment by Mr-Legendary-Pineapple** [comment]
ok thank you

**Comment by Mr-Legendary-Pineapple** [comment]
So just install Git?

**Comment by Mr-Legendary-Pineapple** [comment]
After I install git I still get the error

**Comment by Mr-Legendary-Pineapple** [comment]
@ChaseBrand do you have discord? We could message on there

**Comment by ChaseBrand** [comment]
The game has updated between my original response and now, so even if you built it it wouldn't work. However, the steps for building are as follows.

1. Install [Git](https://git-scm.com/).
2. Clone the repository.
    2a. `git clone https://github.com/BitCrackers/AmongUsMenu.git`
3. Open the `AmongUsMenu.sln` file in Visual Studio. 2019 or 2022 should work as long as you have the C++ SDK and build tools installed.
4. Change the build from Debug x64 to either Release x86 or Release_Version x86. The normal Release version is a .dll file you can use in conjunction with an injector to inject the file into the Among Us process. The version.dll file only needs to be placed next to the game's executable, it will be loaded automatically.

**Comment by Mr-Legendary-Pineapple** [comment]
thank you it works now
