### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by mandeel99** [BitCrackers/AmongUsMenu#228]
Severity	Code	Description	Project	File	Line	Suppression State Error	MSB3073	The command "echo | set /p dummyName=#define GIT_CUR_COMMIT >  user/gitparams.h git rev-parse --verify HEAD >>  user/gitparams.h  echo | set /p dummyName=#define GIT_BRANCH >>  user/gitparams.h git rev-parse --abbrev-ref HEAD >>  user/gitparams.h :VCEnd" exited with code 128.	AmongUsMenu	D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	146	

i got stuck when compiling I tried everything but nothing seems to work

**Comment by ChaseBrand** [comment]
https://github.com/BitCrackers/AmongUsMenu/issues/226

**Comment by mandeel99** [comment]
sadly i Tried it but idk where i cloned it.

**Comment by ChaseBrand** [comment]
I don't know how we're supposed to know where you cloned it. Either find it or re-clone it and follow the instructions in #226.
