### ISSUE TITLE
[Feature] Can we enable Artifacts building for PR requests?

### ISSUE THREAD

**Issue by StupidRepo** [BitCrackers/AmongUsMenu#244]
# I hope my PR I just made adds PR-build support: #245 

I was look at PR #243 and the automatic building and releasing to artifacts was skipped. Can we at least have automatic building for PR’s that we can test?

![E027E404-E329-4C88-9D6E-8BFEEC7471C2](https://user-images.githubusercontent.com/69256931/143677633-13a8df4c-e20b-4909-9229-38f4f71e53af.png)

I think it’ll be nice because then people could download the DLL from that Artifact and test out new changes right then and there!

**Comment by ChaseBrand** [comment]
I believe we’ll be against this, but I could be wrong. We generally like to have a bit of control on what binaries are and are not released so we have a better handle on bug fixes. Oftentimes we push changes that just will NOT work until we fix something else, but we had made enough progress on it that we have to share it with the other devs. We’d hate to start getting flooded with “this build doesn’t work” and “it just crashes” every time we do an initial push after an update.

**Comment by ChaseBrand** [comment]
Aside from what was said above, if it auto-builds for every PR before we can even check the code, that leaves arbitrary code running on our community’s PCs before we get a chance to review it. That’s something we absolutely won’t go for.

**Comment by v0idp** [comment]
We talked about this and decided not to do this. Thanks for your ideas tho.
