### ISSUE TITLE
Killing with the menu causes a ban

### ISSUE THREAD

**Issue by manianac** [BitCrackers/AmongUsMenu#246]
Need to look into why we're now being banned when using the Kill Player button in AUM.  Doesn't look like a distance check, still kills when side by side.

Correction: we will need to use CmdCheckMurder(PlayerControl target) going forward

**Comment by v0idp** [comment]
```cpp
DO_APP_FUNC(0x006E9960, void, PlayerControl_CmdCheckMurder, (PlayerControl * __this, PlayerControl * target, MethodInfo * method));```
it does not return anything. how would you use this ?

**Comment by v0idp** [comment]
```csharp
public override void DoClick()
	{
		if (base.isActiveAndEnabled && this.currentTarget && !this.isCoolingDown && !PlayerControl.LocalPlayer.Data.IsDead && PlayerControl.LocalPlayer.CanMove)
		{
			PlayerControl.LocalPlayer.CmdCheckMurder(this.currentTarget);
			this.SetTarget(null);
		}
	}
```

according to the source code if you click the kill button it will just call the cmdcheckmurder which sends an rpc message to the others with the call id 47 and SendOption 1 and the target set to -1. I checked what handleRPC does when receiving that call id.

in PlayerControl:
```csharp
public void CheckMurder(PlayerControl target)
	{
		if (AmongUsClient.Instance.IsGameOver || !AmongUsClient.Instance.AmHost)
		{
			return;
		}
		if (!target || this.Data.IsDead || !this.Data.Role.IsImpostor || this.Data.Disconnected)
		{
			int num = target ? ((int)target.PlayerId) : -1;
			Debug.LogWarning(string.Format("Bad kill from {0} to {1}", this.PlayerId, num));
			return;
		}
		GameData.PlayerInfo data = target.Data;
		if (data == null || data.IsDead || target.inVent)
		{
			Debug.LogWarning("Invalid target data for kill");
			return;
		}
		this.RpcMurderPlayer(target);
	}
```

not sure how this causes a ban tho.

**Comment by HAF1ZUR** [comment]
Just to note, killing with the menu did not cause a ban yesterday, but it did prevent other imposter teammates from killing anyone

**Comment by DarkPenguin24** [comment]
Didn't get banned for it, Distance doesn't matter as we teleport ourselfs to the target, kill and teleport back right now.
Probably not an Issue anymore?

**Comment by v0idp** [comment]
closing due to issue being stalled
