### ISSUE TITLE
Allow users to turn off "is using AUM" check

### ISSUE THREAD

**Issue by chara26** [BitCrackers/AmongUsMenu#249]

**Comment by chara26** [comment]
I know this should not be considered "an issue".  But recently I met rooms that installed a "mod" which detects AUM and gives auto kicks. I hope there could be an option made to prevent "telling others you are using AUM".

**Comment by v0idp** [comment]
We have this in for a reason. This project is for educational purposes only and if you want to make modifications for your personal use we do not take any responsibility for that.
