### ISSUE TITLE
Live vote count on voting screen

### ISSUE THREAD

**Issue by parsarahimi** [BitCrackers/AmongUsMenu#260]
This is a feature request. On the voting screen there would be a number next to each player showing how many votes they have currently received (Also skip button needs a number too). This can sometimes help you vote for someone (or skip) so that it leads to a tie on purpose.

**Comment by kotae4** [comment]
i'd like to work on this but i'm not sure i have enough time right now.
my idea is to show the mini portraits of players underneath, like how the game does it at the end of the voting period when it tallies the votes
![2021-12-20_15-55-02](https://user-images.githubusercontent.com/83557652/146831650-6d98d7aa-a131-4d38-a9b7-5a4a701637bf.jpg)

**Comment by v0idp** [comment]
I'll take a look in the source code and see how it's done.

**Comment by v0idp** [comment]
this is what I was able to find:
```csharp
private void BloopAVoteIcon(GameData.PlayerInfo voterPlayer, int index, Transform parent)
	{
		SpriteRenderer spriteRenderer = Object.Instantiate<SpriteRenderer>(this.PlayerVotePrefab);
		if (PlayerControl.GameOptions.AnonymousVotes)
		{
			PlayerControl.SetPlayerMaterialColors(Palette.DisabledGrey, spriteRenderer);
		}
		else
		{
			PlayerControl.SetPlayerMaterialColors(voterPlayer.DefaultOutfit.ColorId, spriteRenderer);
		}
		spriteRenderer.transform.SetParent(parent);
		spriteRenderer.transform.localScale = Vector3.zero;
		base.StartCoroutine(Effects.Bloop((float)index * 0.3f, spriteRenderer.transform, 1f, 0.5f));
		parent.GetComponent<VoteSpreader>().AddVote(spriteRenderer);
	}
```
