### ISSUE TITLE
Vent issue still exists

### ISSUE THREAD

**Issue by chara26** [BitCrackers/AmongUsMenu#261]
Disable Unlock vents as imposter will cause imposter's vent option disappear (imposter can't vent lol)
enable unlock vents as engineer and engineer vent countdown is set to 30s and won't go down(engineer can't vent lol)

**Comment by manianac** [comment]
I could not duplicate the impostor bug
https://user-images.githubusercontent.com/2092573/146681134-7caa93b8-f6bb-43f6-9326-2a6408aa4da3.mp4

I have duplicated the Engineer bug, it seems Innersloth changed the behaviour of the vent.  I will look into if we can workaround this, or we will just change it to use the impostor button.

**Comment by chara26** [comment]
pls Try enable the option before entering game and disable it in game as imposter.

**Comment by manianac** [comment]
What version of AUM are you using?

**Comment by chara26** [comment]
1.0.15 debug

**Comment by chara26** [comment]
you should be shapeshifter to toggle the bug

**Comment by chara26** [comment]
![image](https://user-images.githubusercontent.com/62291318/146682779-de82b84e-01c3-4892-9767-e071bd73dfcd.png)

**Comment by manianac** [comment]
Ok, confirmed this is only a problem with a shapeshifter

**Comment by StupidRepo** [comment]
Hey does the shape shifting bug that bans you for "hacking" still exist?

**Comment by chara26** [comment]
> Hey does the shape shifting bug that bans you for "hacking" still exist?

I don't know what you mean...
Pls open another issue and describe your problem more clearly.

**Comment by chara26** [comment]
Still not fixed in 1.0.16

**Comment by v0idp** [comment]
@manianac

**Comment by chara26** [comment]
> It disappears with shapeshifter.
> 
> Still working on engineer changes in new version.

Engineer still suffers countdown.

**Comment by chara26** [comment]
![image](https://user-images.githubusercontent.com/62291318/146950767-45309fab-eded-4081-b14f-e7de38a7a965.png)

**Comment by manianac** [comment]
Yes. Please read my previous statement

**Comment by chara26** [comment]
You mean disable the feature to use the normal engineer?
I mean the option still locks engineer cd at 30

**Comment by manianac** [comment]
No, we are still working on the issue.  The 1.0.16 did not fix this.

**Comment by chara26** [comment]
Huh so im leaving the issue here.
