### ISSUE TITLE
Got Banned When I Cleared All My Tasks During a Metting

### ISSUE THREAD

**Issue by Bj007pro** [BitCrackers/AmongUsMenu#265]
![image](https://user-images.githubusercontent.com/24400879/147168193-f2dc7820-1d32-4ae3-ae82-16d63d5dfc40.png)

I was dead and the Scientist if that helps.

**Comment by manianac** [comment]
TODO: we need to rate limit the task completed calls.  These bans likely happen when over a certain number of tasks remaining.

**Comment by DarkPenguin24** [comment]
Tried it today, could clear 10 tasks without any issue during the meeting while being alive.
Seems to be some check on whether you are dead or not.

**Comment by DarkPenguin24** [comment]
resolved, will be published with the next update
