### ISSUE TITLE
Disable cast protect on imposters

### ISSUE THREAD

**Issue by parsarahimi** [BitCrackers/AmongUsMenu#268]
Forgot to mention this a few days ago because I don't usually play Guardian Angel.

**Comment by v0idp** [comment]
can you ellaborate on this ? Not sure what you mean...

**Comment by parsarahimi** [comment]
you can cast protection as a guardian on imposters, that would be a waste of your ability of course. This happens quite frequently too, because the imposter is following the crew to kill them.

**Comment by v0idp** [comment]
why would we disable a gameplay feature ? I'm kinda confused about this. You can see who is imposter with the menu anyways...

**Comment by parsarahimi** [comment]
You have to play as guardian angel to understand probably, but when you want to protect someone and you're following them and the imposter is also following them, the imposter could accidently get the protection instead because they sometimes be clipping inside each other and at that point you have no control.

**Comment by v0idp** [comment]
I can see what you mean now. But I will have to decline this feature request due to the nature of the feature of removing functionality to cover for your own mistakes.
