### ISSUE TITLE
Using version.dll causes game to crash

### ISSUE THREAD

**Issue by Sinnerman27** [BitCrackers/AmongUsMenu#269]
I'm not sure if I need some sort of prerequisite, but putting version.dll in the Among Us folder causes it to crash. I made sure to put it in the root folder like other hacks but for some reason it just refuses to work. Other dll works fine.

**Comment by chara26** [comment]
First check if you have installed all the c++ runtime

Your game is epic or steam? x32 build or x 64? 
is the menu you using the newest?
send us "aum-log.txt" in the root folder if it generates

As for me,the menu works well.

**Comment by Sinnerman27** [comment]
Just updated to the latest runtime and still crashing. Game is Steam 32 bit. The menu is the newest v1.0.17
[aum-log.txt](https://github.com/BitCrackers/AmongUsMenu/files/7772726/aum-log.txt)
.

**Comment by v0idp** [comment]
are u using the steam version of the game?

**Comment by Sinnerman27** [comment]
Yeppers

**Comment by v0idp** [comment]
the easiest way to find out what the issue is would be if you start up visual studio yourself, attach a debugger to the among us process and then inject the debug amongusmenu.dll into the game. this will show you in visual studio where it breaks.

**Comment by manianac** [comment]
I was unable to duplicate this testing the version build.  One thing I had to do in the past to debug this build was insert a `DebugBreak()` statement to force the debugger to be attached before continuing with the initialization.

**Comment by Sinnerman27** [comment]
I'll do all that when I'm back from vacation in 5 days. Will let you know.

**Comment by Bj007pro** [comment]
I've had this error pop-up time-to-time when launching the game using version.dll.
![image](https://user-images.githubusercontent.com/24400879/147398639-3e690de4-8650-4cfe-a989-7489355988cd.png)

Apologies' in advance if I should created another issue about this but I thought since this is similar to what OP was talking about so I posted in this issue.

This happens only rarely when starting the game,

**Comment by manianac** [comment]
https://github.com/BitCrackers/AmongUsMenu/blob/main/framework/il2cpp-helpers.cpp#L236

We should probably increase the timeout then.  This was created originally as we were attempting to access game pointers before they were initialized with a version.dll build, cctor_finished causes the menu to wait until they're available.

@v0idp if you're good with it, I think we add all the cctor_finished calls back in and then increase the timeout to something like 10 seconds.

**Comment by manianac** [comment]
Also when this happens it would be helpful to post up your aum_log.txt files

**Comment by v0idp** [comment]
> https://github.com/BitCrackers/AmongUsMenu/blob/main/framework/il2cpp-helpers.cpp#L236
> 
> We should probably increase the timeout then. This was created originally as we were attempting to access game pointers before they were initialized with a version.dll build, cctor_finished causes the menu to wait until they're available.
> 
> @v0idp if you're good with it, I think we add all the cctor_finished calls back in and then increase the timeout to something like 10 seconds.

I agree, feel free to add that into your current vent fix

**Comment by Sinnerman27** [comment]
I know I can't contribute much right now but goddamn it's nice seeing hack creators actually on top of their stuff.

**Comment by toc8730** [comment]
I'm having this issue too, a temporary fix might be to run the actual exe (not launching it with steam), but you might have to play with a temporary account

**Comment by kotae4** [comment]
> 



> https://github.com/BitCrackers/AmongUsMenu/blob/main/framework/il2cpp-helpers.cpp#L236
> 
> We should probably increase the timeout then. This was created originally as we were attempting to access game pointers before they were initialized with a version.dll build, cctor_finished causes the menu to wait until they're available.
> 
> @v0idp if you're good with it, I think we add all the cctor_finished calls back in and then increase the timeout to something like 10 seconds.

i added a bunch of logging code when i removed those cctor_finished assertions and confirmed that the expression never evaluates to true at any point during gameplay. i suspect it's some internal change in unity engine. increasing the timeouts will still lead to assertion fail.

**Comment by v0idp** [comment]
> > 
> 
> > https://github.com/BitCrackers/AmongUsMenu/blob/main/framework/il2cpp-helpers.cpp#L236
> > We should probably increase the timeout then. This was created originally as we were attempting to access game pointers before they were initialized with a version.dll build, cctor_finished causes the menu to wait until they're available.
> > @v0idp if you're good with it, I think we add all the cctor_finished calls back in and then increase the timeout to something like 10 seconds.
> 
> i added a bunch of logging code when i removed those cctor_finished assertions and confirmed that the expression never evaluates to true at any point during gameplay. i suspect it's some internal change in unity engine. increasing the timeouts will still lead to assertion fail.

maybe delay for longer like 10sec and remove the assertion all along then ?

**Comment by Sinnerman27** [comment]
I apologize for being gone so long. This issue seems to have fixed itself, although I don't know how. I do have one more question though.

Would it be possible for me to, in some way, remove all features from this hack but one? I just want to be able to tell who's using this hack in-game, but without all the extra ESP and whatnot. I have no experience in coding or changing code so I don't know if this is possible or not.

**Comment by DarkPenguin24** [comment]
Just use it as it is and don't enable any feature?

**Comment by v0idp** [comment]
we won't do any changes for you, it's open source. not knowing is not an excuse. closed

**Comment by Sinnerman27** [comment]
Lol I wasn't making an excuse for anything, I literally just asked if it would be possible. I certainly didn't ask you to do it for me, so I don't know what your deal is.

**Comment by ChaseBrand** [comment]
> Lol I wasn't making an excuse for anything, I literally just asked if it would be possible. I certainly didn't ask you to do it for me, so I don't know what your deal is. I thought you were cool but you don't need to be rude about it.

Yeah sorry, that came off as rather aggressive; sorry. We get questions all the time about how to add/remove features, and we generally don't support custom builds since we just _can't_ support them, we have no idea what people have changed in it and we like to keep the menu out of the hands of people who would sell it.

In response to the question- of course it's possible! The easiest way however is to just use the menu and disable everything except the AUM check. It would save you a lot of work versus removing everything else.

**Comment by Sinnerman27** [comment]
That's understandable, thank you. I'm fully willing to take the time to learn and do it myself, I just wanted to be sure it would be possible to do in the first place.
