### ISSUE TITLE
64-bit support

### ISSUE THREAD

**Issue by KarmaMod** [BitCrackers/AmongUsMenu#270]
Xenos won't let me inject 32-bit dll into 64-bit process. Can you add 64-bit support?

I'm using UWP version of Among Us as it was included in my Xbox game pass.

**Comment by manianac** [comment]
Given all of the other distributions are 32-bit, I don't think we may support this.  You can try compiling yourself though.

**Comment by v0idp** [comment]
We don't support this sorry. You will have to compile it yourself in 64bit. Keep in mind that the version.dll oke won't work since the proxy functions are using inline assembly which is not supported by 64bit

**Comment by KarmaMod** [comment]
32-bit is old so this project must support 64-bit

I can't compile it myself because i'm getting a lot of errors. I'm not familar with VS

![image](https://user-images.githubusercontent.com/88159598/148398078-db326de3-4a18-43cd-815b-6cc9b7ff6b7e.png)

**Comment by manianac** [comment]
While old, every other copy of the game is 32-bit. Until Innersloth decides to do something else, we will only support 32 bit.
