### ISSUE TITLE
My Game Keeps Crash Over and Over With the Menu. I Don't Know What's Different Than Last Night When It Was Working.

### ISSUE THREAD

**Issue by Bj007pro** [BitCrackers/AmongUsMenu#271]
It was opening fine and not crashing last night, I put my PC to sleep mode like I usually do before I go to bed, and now today it keeps crashing over and over during startup.

Here's my AUM log:
[aum-log.txt](https://github.com/BitCrackers/AmongUsMenu/files/7794499/aum-log.txt)

**Comment by v0idp** [comment]
duplicate of #269
