### ISSUE TITLE
 Shapeshifting doesn't change name

### ISSUE THREAD

**Issue by FloydDeservedIt** [BitCrackers/AmongUsMenu#272]
Shapeshifting doesn't change name for newest version

**Comment by manianac** [comment]
What are you wanting to happen?

- That the name changes to the player the impostor shapeshifted as?

- The name stays as the original impostor's name.

**Comment by DarkPenguin24** [comment]
right now the name stays as is (original name of imposter).
he probably wants to see the shapeshifted name

**Comment by FloydDeservedIt** [comment]
> What are you wanting to happen?
> 
> * That the name changes to the player the impostor shapeshifted as?
> * The name stays as the original impostor's name.

The name stays as the original player name for other shape shifters and me when i am the shapeshifter. Is the name not changing when i shapeshift myself or is that supposed to happen and other players do see the name different

**Comment by FloydDeservedIt** [comment]
> right now the name stays as is (original name of imposter). he probably wants to see the shapeshifted name

?

**Comment by FloydDeservedIt** [comment]
> What are you wanting to happen?
> 
> * That the name changes to the player the impostor shapeshifted as?
> * The name stays as the original impostor's name.

?

**Comment by ChaseBrand** [comment]
Fixed in #275.
