### ISSUE TITLE
Bug where imposters cannot kill

### ISSUE THREAD

**Issue by ColdKidYT** [BitCrackers/AmongUsMenu#274]
if i am host and select imposters they cannot kill. they can vent sabotage but cant kill and i can kill

**Comment by chara26** [comment]
You mean when they kill they got banned?

**Comment by ColdKidYT** [comment]
The kill button is just greyed out for them

**Comment by DarkPenguin24** [comment]
Do you have more Information on this issue?
Can you post a screenshot of your lobby settings?
Which Role did the Imposter get? "Normal" Imposter or Shapeshifter?
Was the Lobby host Imposter or another player?
Can you post aum-logs.txt? (located inside the game directory)

**Comment by ColdKidYT** [comment]
The imposter was another player and they got normal imposter, when another player clicks the kill button it does nothing.
if me(lobby host) and another player are imposter then only I can kill whereas the other player cannot kill
I attached all the files and video of what happens ingame. In the video i hosted off of my pc and made myself imposter on my phone
https://streamable.com/kxt133
![amonguslobbysettings](https://user-images.githubusercontent.com/32724498/151681517-c4d27206-be8a-46e7-90a9-b9956ca967a9.PNG)
[aum-log.txt](https://github.com/BitCrackers/AmongUsMenu/files/7965016/aum-log.txt)

**Comment by DarkPenguin24** [comment]
Does it still happen with v1.0.18?

**Comment by ColdKidYT** [comment]
Yeah just tested and still happens.

**Comment by ColdKidYT** [comment]
Just tested again with my friend whos on console and he was able to kill. Maybe its because im on phone?

**Comment by ColdKidYT** [comment]
Tested more.
If i am host and pick myself to be imposter and another player. They can only kill after i have killed a different player. if they try to kill before me then nothing happens and they cant kill rest of game.

**Comment by DarkPenguin24** [comment]
Does that also happen if u don't use aum?

**Comment by v0idp** [comment]
closing this due to issue being stalled
