### ISSUE TITLE
steamworks bug

### ISSUE THREAD

**Issue by Craudion** [BitCrackers/AmongUsMenu#281]
Everytime i put the mod menu to the among us folder, I get this 
![image](https://user-images.githubusercontent.com/97497205/149002446-913212ab-c4db-4804-ab6b-42a5c74cb1b8.png)
this kinda annoys me, i cant change my name and im usually stuck to quick play, rip #

**Comment by Craudion** [comment]
anyone?

**Comment by manianac** [comment]
Does the game work without AUM in use?  Is this a cracked copy?

You can change your name with the menu without signing onto Steam.

**Comment by DarkPenguin24** [comment]
maybe auth before injecting aum?

**Comment by DarkPenguin24** [comment]
can you post your aum-log.txt which is located inside the game directory?
