### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by s4cta3l** [BitCrackers/AmongUsMenu#286]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "echo | set /p dummyName=#define GIT_CUR_COMMIT >  gitparams.h
git rev-parse --verify HEAD >>  gitparams.h

echo | set /p dummyName=#define GIT_BRANCH >>  gitparams.h
git rev-parse --abbrev-ref HEAD >>  gitparams.h
:VCEnd" exited with code 9009.	AmongUsMenu	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	145	

Sorry i dont know shit about code

**Comment by ChaseBrand** [comment]
[Install Git](https://git-scm.com/downloads).
