### ISSUE TITLE
Menu does not display

### ISSUE THREAD

**Issue by Sasha98630147** [BitCrackers/AmongUsMenu#290]
Tried both versions (debug, release), tried compiling dll files myself, but the menu still does not appear in the game. Injection occurs with errors. Enclosing the log file.
[aum-log.txt](https://github.com/BitCrackers/AmongUsMenu/files/7918330/aum-log.txt)

**Comment by toc8730** [comment]
Press the "INSERT" key on your keyboard to make it show up - for me, the insert key is in the top row of my keyboard, idk about you

**Comment by Sasha98630147** [comment]
None of the keys work, neither delete nor insert

**Comment by Sasha98630147** [comment]
Problem solved. In case anyone is wondering, the problem was caused by the msi afterburner riva statistic server. After closing the program, the menu appeared
