### ISSUE TITLE
Outfits not saving anymore

### ISSUE THREAD

**Issue by v0idp** [BitCrackers/AmongUsMenu#296]
Can anyone confirm that Outfits don't save anymore if AUM is active and we change the outfit?

**Comment by DarkPenguin24** [comment]
no, outfit is saved if you change it while using aum, unless we have a special function to change it inside the menu?
just used the wardrobe and it's saving

**Comment by v0idp** [comment]
I tried changing outfits and then quitting but I always end up with no outfit at all after restarting. I mean we do hook some of the outfit functions not sure if that influences anything. can you double check that ?
