### ISSUE TITLE
Colors on radar and replay are darkened

### ISSUE THREAD

**Issue by 4310V343k** [BitCrackers/AmongUsMenu#299]
| Normal | Radar |
:-------------------------:|:-------------------------:
![](https://i.imgur.com/MHC0j5z.png) | ![](https://i.imgur.com/yQLKfLd.png)
![](https://i.imgur.com/MC2UZhB.png) | ![](https://i.imgur.com/6qVwiOs.png)

**Comment by v0idp** [comment]
I'll look into it and try to match the colors better.
