### ISSUE TITLE
[Feature] Print Basic game information on console

### ISSUE THREAD

**Issue by chara26** [BitCrackers/AmongUsMenu#301]
**This is a feature request**
Normally **adv settings** (example:engineer vent cd,shapeshifter cd) of the roles aren't showed to players.
So I suggest AUM print these settings on the console everytime the game starts or work out some other ways to tell user these information.
This feature should be very helpful in some extreme conditions

Settings to be printed:
engineer vent cd , engineer in vent cd , guariden angle protection cd , shapeshifter cd

**Comment by v0idp** [comment]
Additionally I was thinking about adding sabotage, sabotage repair and door close and open events

**Comment by kotae4** [comment]
The game info stuff might work better as a new tab on menu named like 'Info' or something. That way you don't have to scroll through the console to see it every time.

**Comment by v0idp** [comment]
or we can make a permanent space in the console for that. the console doesnt need to take up the whole space. we have way too many tabs tbh. we might want to think about grouping them in dropdown lists at this point
