### ISSUE TITLE
Awesome! U assigned 4 imposters!

### ISSUE THREAD

**Issue by chara26** [BitCrackers/AmongUsMenu#307]
![QQ截图20220309125750](https://user-images.githubusercontent.com/62291318/157376902-02ebfd68-f6f0-446a-afd3-63df78f5b621.png)
All on deafult config(haven't changed anything)
This is a wonderfunl feature!  Please keep it working!

**Comment by v0idp** [comment]
Is this actually an issue ? I'm not sure what's this about.

**Comment by chara26** [comment]
ok deleting this one

**Comment by cddjr** [comment]
这个其实是AUM的bug，哈哈。
在实现分配角色的时候逻辑有瑕疵，不过我几乎不做房主，所以没怎么去分析这里面的逻辑。

**Comment by kotae4** [comment]
> 这个其实是AUM的bug，哈哈。 在实现分配角色的时候逻辑有瑕疵，不过我几乎不做房主，所以没怎么去分析这里面的逻辑。

does the issue still exist after this commit?
https://github.com/BitCrackers/AmongUsMenu/commit/3af90f4f3a7bff218bf20b0dee8edb31ee7832df
