### ISSUE TITLE
Role reveal bug on shapeshifter

### ISSUE THREAD

**Issue by chara26** [BitCrackers/AmongUsMenu#310]
When Role reveal is disabled. shapeshifter's name is white . But if it shifted to others, the name will appear red even if Role reveal is disabled.

**Comment by DarkPenguin24** [comment]
```
Color32 roleColor = app::Color32_op_Implicit(Palette__TypeInfo->static_fields->White, NULL);
if (State.RevealRoles)
	roleColor = app::Color32_op_Implicit(GetRoleColor(playerData->fields.Role), NULL);
else if (PlayerIsImpostor(localData) && PlayerIsImpostor(playerData))
	roleColor = app::Color32_op_Implicit(Palette__TypeInfo->static_fields->ImpostorRed, NULL);
```

How can that change the color to red for a shapeshifted person?

**Comment by v0idp** [comment]
I wonder what was the idea of doing this check ? ``PlayerIsImpostor(localData) && PlayerIsImpostor(playerData)``

**Comment by v0idp** [comment]
I mean in default behaviour when you're impostor and the target is impostor he will be shown in read text color anyways. why do we do that on top again ?

**Comment by DarkPenguin24** [comment]
cause the game doesn't reset the color if we change from reveal roles to not revealing roles?

**Comment by v0idp** [comment]
oh yea I remember totally forgot about that. 🤦

**Comment by DarkPenguin24** [comment]
I never noticed any issue with this logic and it has been in the menu for over a month now.
It's probably something else that is causing an issue here.

Ping? Unshifting / Shifting before the next update is done? Issue with role assignment?
Could probably be anything, but we need more information....
Can u tell us more chara? and more importantly can you reproduce this issue?

**Comment by chara26** [comment]
Closing this , i litterly cannot do the bug again...
Sorry for disturbing you.
