### ISSUE TITLE
Role assignment: 4players -- assigned 2 imposters

### ISSUE THREAD

**Issue by chara26** [BitCrackers/AmongUsMenu#311]
4 players in game and imposter set to one , aum generates 2 imposters ,causing instant win

**Comment by v0idp** [comment]
also let us know which version you're exactly using. post debug logs.

**Comment by chara26** [comment]
#312 I didn't know this before
I only meet this in local games and I can't access host bar.
But AUM did change the original Role Assignment behavior.
I'm not able to test this in online games.

**Comment by chara26** [comment]
Probably no need to continue this issue. You aren't meeting 4 players room in online games
