### ISSUE TITLE
Cannot use Host in Local games

### ISSUE THREAD

**Issue by chara26** [BitCrackers/AmongUsMenu#312]
I'm not sure whether this is a bug, but host tab aren't working in local games
![QQ截图20220311022053](https://user-images.githubusercontent.com/62291318/157729324-0425e8f5-cdb5-4938-87d7-806a42ec745f.png)
.

**Comment by chara26** [comment]
Also players tab disappears. maybe u just don't support this?

**Comment by v0idp** [comment]
amongusmenu was not written with local games in mind.
