### ISSUE TITLE
Game crashes when often impersonating people (BUG)

### ISSUE THREAD

**Issue by AAAAAXfda** [BitCrackers/AmongUsMenu#314]
**So after some time when I try to impersonate someone my game crashes**
![VHa9Wv3pUG](https://user-images.githubusercontent.com/65740278/158053710-ba86b6e4-d8eb-4016-9135-3bf30d76b4c5.png)
**Debug information (when crashed):**
![ve8g14TVJ6](https://user-images.githubusercontent.com/65740278/158053743-73cd01b7-9c1a-4cd3-a6d0-0b1295d9eb23.png)

**Comment by kotae4** [comment]
Do you still experience this with the lastest (v1.1.7) build?

**Comment by AAAAAXfda** [comment]
> Do you still experience this with the lastest (v1.1.7) build?

nope, I suppose it's fixed
