### ISSUE TITLE
Delayed random crashes

### ISSUE THREAD

**Issue by parsarahimi** [BitCrackers/AmongUsMenu#319]
The game crashes after like 30 minutes, quite consistently too. This didn't happened in the past, probably to do with the new replay feature causing memory leaks. Also the replay feature trace line doesn't get washed off after X amount of seconds when you're panning the progress bar, it only works in live mode.

**Comment by v0idp** [comment]
you probably crash after a meeting I assume ?

**Comment by parsarahimi** [comment]
No actually, happens in middle of the game. Maybe it was because someone reported or called meeting but crashes right at that moment, but I'm just guessing, the last frame I see upon crash is me walking in the hallway (usually)

**Comment by v0idp** [comment]
do you have "show dead bodies" in radar or your console open while playing ?

**Comment by parsarahimi** [comment]
I do have show dead bodies checked in radar, the console is usually closed while not in meeting

**Comment by parsarahimi** [comment]
No crashes even after a few hours, but now I noticed another bug, time to make a new issue...
