### ISSUE TITLE
Setting Player Speed to Low Values Causes Other Crewmates to Teleport

### ISSUE THREAD

**Issue by RealMVC** [BitCrackers/AmongUsMenu#32]
If you go into the game tab and set player speed to a low value (like 0.5x), and join an online game (not as host), other players will appear to be teleporting around, because your player speed and their player speed are different. Not sure if this can be fixed, but something to look into.

**Comment by OsOmE1** [comment]
I remember when I made an external menu I did the speed hack by taking the PlayerPhysics from the PlayerControl object and changing the PlayerPhysics__Fields.Speed to a higher value. Maybe this would work

**Comment by KcTec90** [comment]
same i noticed that as well :)
