### ISSUE TITLE
Some events are not registered/registered improperly

### ISSUE THREAD

**Issue by 4310V343k** [BitCrackers/AmongUsMenu#321]
![](https://i.imgur.com/wAQLSNS.png)

(mostly report and meeting events)

**Comment by v0idp** [comment]
I notiticed this too, I'm not sure why but for some reasons not all functions get triggered when they should. they're all properly triggered. maybe something with the output ?! If somebody could replicate I will take a look

**Comment by 4310V343k** [comment]
> I notiticed this too, I'm not sure why but for some reasons not all functions get triggered when they should. they're all properly triggered. maybe something with the output ?! If somebody could replicate I will take a look

Possible replication is multiple people pressing the button/reporting the body.

IIRC the icons on the replay show up correctly (except #300, but that's another issue), so this may be an issue with the output
