### ISSUE TITLE
People are not updated on live replay after certain events

### ISSUE THREAD

**Issue by 4310V343k** [BitCrackers/AmongUsMenu#322]
- After a player has left
- If a player is AFK and a meeting starts

Replays use only move events, but not left/teleported (to a meeting) ones

**Comment by v0idp** [comment]
can you elaborate on that a bit better and show some examples ? I'm not sure what exactly you mean

**Comment by 4310V343k** [comment]
> can you elaborate on that a bit better and show some examples ? I'm not sure what exactly you mean

Maybe my wording was a bit bad, sorry

If someone leaves the game, their icon on the replay will remain in the same place till the end of the game. An icon indicating a leave would be more useful

Also, when the meeting starts, every player is teleported to the lobby, but their icons on the replay stay in the place as they were before the meeting. That is the intended behaviour, BUT when the meeting ends, the icons are still not moved to their actual player, and will not move until the player itself starts moving

**Comment by v0idp** [comment]
> > can you elaborate on that a bit better and show some examples ? I'm not sure what exactly you mean
> 
> Maybe my wording was a bit bad, sorry

Sorry for the late reply.

> If someone leaves the game, their icon on the replay will remain in the same place till the end of the game. An icon indicating a leave would be more useful

maybe we can add a disconnect icon over their last known position indicating that they left.

> Also, when the meeting starts, every player is teleported to the lobby, but their icons on the replay stay in the place where they were before the meeting. That is the intended behaviour, BUT when the meeting ends, the icons are still not moved to their actual player, and will not move until the player itself starts moving

yes that is intended behaviour. the reason why this happens is because the new moving event will only trigger if the player moves. this helps to reduce to save a huge amount of move events.

**Comment by 4310V343k** [comment]
> maybe we can add a disconnect icon over their last known position indicating that they left.

yeah, that's what i thought would fix this

> yes that is intended behaviour. the reason why this happens is because the new moving event will only trigger if the player moves. this helps us to reduce huge amounts of move events.

well, one possible solution is to force a move event after a meeting

another one is to detect teleports and make them a separate event (i mean, the players do move in the game, right?)

**Comment by v0idp** [comment]
Well we were thinking about not drawing the big jumps. There is also still missing timestamp checks for the meetings I believe. That's something we will look into and improve the visualization for.

**Comment by p3tt3** [comment]
> * After a player has left
> * If a player is AFK and a meeting starts
> 
> Replays use only move events, but not left/teleported (to a meeting) ones

what dll injector you are using and what dll you inject AMongUsMenu..dll or version.dll?

**Comment by ChaseBrand** [comment]
Stale.
