### ISSUE TITLE
Doesn't inject in latest Among us version

### ISSUE THREAD

**Issue by SlowLow32** [BitCrackers/AmongUsMenu#326]
[INFO - AUM - Run]
        AmongUsMenu - Mar 30 2022 - 17:51:22
        Build: Debug
        Commit: b99ea4e21ae016a4e6254970c65a391b79a1829a - HEAD
        Among Us Version: 2022.3.29

[INFO - AUM] Unable to load settings.json
[DEBUG - AUM - cctor_finished] Class AmongUsClient Has Static Constructor: false
[DEBUG - AUM - Run] Game::pAmongUsClient is 0x24660E18 -> 0x20F59840
[DEBUG - AUM - cctor_finished] Class GameData Has Static Constructor: true
[DEBUG - AUM - Run] Game::pGameData is 0x0CB02270 -> 0x00000000
[DEBUG - AUM - cctor_finished] Class PlayerControl Has Static Constructor: true
[DEBUG - AUM - Run] Game::pGameOptionsData is 0x0CB04C44 -> 0x21200C30
[DEBUG - AUM - cctor_finished] Class PlayerControl Has Static Constructor: true
[DEBUG - AUM - Run] Game::pAllPlayerControls is 0x0CB04C48 -> 0x2451A120
[DEBUG - AUM - cctor_finished] Class PlayerControl Has Static Constructor: true
[DEBUG - AUM - Run] Game::pLocalPlayer is 0x0CB04C40 -> 0x00000000
[DEBUG - AUM - cctor_finished] Class ShipStatus Has Static Constructor: false
[DEBUG - AUM - Run] Game::pShipStatus is 0x0CB022D8 -> 0x00000000
[DEBUG - AUM - cctor_finished] Class LobbyBehaviour Has Static Constructor: false
[DEBUG - AUM - Run] Game::pLobbyBehaviour is 0x0CB022E0 -> 0x00000000
[DEBUG - AUM - cctor_finished] Class SaveManager Has Static Constructor: true
Failed to hook HatManager_c__GetUnlockedHats_b__11_0

**Comment by kotae4** [comment]
https://github.com/BitCrackers/AmongUsMenu/pull/327
