### ISSUE TITLE
kill and vent button randomly becomes disabled as imposter

### ISSUE THREAD

**Issue by parsarahimi** [BitCrackers/AmongUsMenu#330]
So the kill button and vent button become grayed out permanently and wont work at some point in the game, it never happens at the start. Doesn't happen in every game. Sabotage always works. 
Killing people using the menu commands which remains the only option at that point, will result in a kick. This kind of kick happened in the past when you killed other crewmates as crewmate by enforcing the kill command, so it might be because your role has changed mid game for some reason (from imposter to crewmate).

**Comment by StupidRepo** [comment]
Yeah, this is annoying. You can still kill/vent using the keybinds though.

**Comment by kotae4** [comment]
i have a hunch this happens when the host disconnects and a host migration occurs.
has anyone noticed this happening *without* aum? whenever it happens everyone else in the lobby seems familiar with the bug, so it makes me think it might be a game bug.

**Comment by parsarahimi** [comment]
You're right, the kick itself from using the command menu to kill a player kicks you regardless if you're close or if your button is broken.

**Comment by p3tt3** [comment]
> 

what dll injector you are using and what dll you inject AMongUsMenu..dll or version.dll?

**Comment by MaguirePool** [comment]
> > 
> 
> what dll injector you are using and what dll you inject AMongUsMenu..dll or version.dll?

KNKCHEATS INJECTOR

amongusmenu.dll
