### ISSUE TITLE
i need help idk how it works

### ISSUE THREAD

**Issue by kyleparker134** [BitCrackers/AmongUsMenu#346]
i cant seem to get it working (v2022.3.29s)

**Comment by ChaseBrand** [comment]
We have two options here. 

1) We wait until I or a member of the team derive magical powers to debug and test your issues for you without you telling us what they are, posting a log, or giving us any information that lets us know what is or is not going on.

2) You tell us what your issues are, post a log, and give us information that lets us know what is or is not going on.

I’m down for either, but one will be quicker!

**Comment by kyleparker134** [comment]
sorry, i have put both .dlls into the home folder (where the exe file is located) and the menu is not showing up. i also tried an injector but still nothing.

**Comment by ChaseBrand** [comment]
So you only need to place one .dll in the folder where the game executable lies, the `version.dll`. Once you launch the game, press the Delete key.

And yes, the images are what it looks like.

**Comment by kyleparker134** [comment]
thank you very much, i thought you had to have both in. thanks for your time

**Comment by ChaseBrand** [comment]
Sure!
