### ISSUE TITLE
Crashes while entering a game

### ISSUE THREAD

**Issue by macbookprousr** [BitCrackers/AmongUsMenu#353]
[aum-log.txt](https://github.com/BitCrackers/AmongUsMenu/files/8501024/aum-log.txt)
Happens every time i tried to enter a game.

**Comment by cddjr** [comment]
你是中国🇨🇳人吧？ 那我就用中文与你交流了。
你可以提交这个目录内的文件
%TEMP%\Innersloth\Among Us\Crashes

里面形如Crash_2022-04-17xxxx这样的文件夹，选一个最新的打包发到这里我看看

**Comment by CychUC** [comment]
Looks like your game version is pretty out of date. Your log shows 2022.2.8, but the current version is 2022.3.29.

**Comment by macbookprousr** [comment]
Fixed it nvm

**Comment by macbookprousr** [comment]
Get sth strange in my sourcecode
