### ISSUE TITLE
Question: Does this work with the Game Pass Pc Version?

### ISSUE THREAD

**Issue by zeldaking** [BitCrackers/AmongUsMenu#354]
I was trying to use this on my computer and it didn't work at all. Is the mod compatible with the Pc Game Pass Version?

**Comment by chara26** [comment]
Aum aren't supporting x64 builds officially, so you aren't able to use aum on UMP version.
You can still try make a x64 build yourself.

**Comment by v0idp** [comment]
No it won't work with Microsoft Platform due to the nature with how they encrypt and wrap all the games on their platform with UWP. Even if we build it in x64 it still won't work.
