### ISSUE TITLE
Replay Showing Dead Player in whole Timeline

### ISSUE THREAD

**Issue by v0idp** [BitCrackers/AmongUsMenu#359]
Player Icons on Replay Map will show as dead if they died no matter which timestamp.
this needs to be fixed so the dead icon only starts from the timestamp where the player died.

**Comment by FerhatCatak** [comment]
u r currently probably using a isDead flag, which is time independent and therefor can only show if the player died at all during the recorded game. For this to change the simplest solution would be to have a timestamp attribute called "diedAt" for every player which is undefined as long the player is alive and set to a specific timestamp as soon the player died. This could be used in the render cycle of the Replay Map. 

Another option would be to save the "DEATH"-Event of a specific player like every other event in the recording for the replay map and still use the boolean "isDead" flag for every single player, but which will only get set to true when the "DEATH"-Event for that specific player occurs in the replayed map and no longer represent the general state that the player died at all in that game at any time.
