### ISSUE TITLE
nice virus lmfaooooooooo

### ISSUE THREAD

**Issue by firefoxnightlymozzila** [BitCrackers/AmongUsMenu#361]
https://www.virustotal.com/gui/file/91f3a08c29e3925b71387b55c5c0ffa5069ec3fb662f228e1ff05f906077f26e

**Comment by DarkPenguin24** [comment]
false positives, which is to be expected.
u really think we would code open source and than put malicious code in there? lmfao

**Comment by v0idp** [comment]
The Releases are compiled on the GitHub server directly from the open source code of the repo.
