### ISSUE TITLE
i inject the dll and the game crash!

### ISSUE THREAD

**Issue by chinabestcountry** [BitCrackers/AmongUsMenu#365]
I injected dll in 2022.2.8, but it crashed, here is a screenshot of the error:
![image](https://user-images.githubusercontent.com/94364764/168426786-094b2274-266e-479a-aac7-a99dc2fae1b5.png)
![_69_ )1R{1V5X}J QP 3)A2](https://user-images.githubusercontent.com/94364764/168426854-7b55f991-5db6-4d9a-9ea9-eeee0c5c9703.png)
![OI injected dll in 2022.2.8, but it crashed, here is a screenshot of the error:
![image](https://user-images.githubusercontent.com/94364764/168426786-094b2274-266e-479a-aac7-a99dc2fae1b5.png)
![_69_ )1R{1V5X}J QP 3)A2](https://user-images.githubusercontent.com/94364764/168426854-7b55f991-5db6-4d9a-9ea9-eeee0c5c9703.png)
`G {28Q6 UXC%} `H{8](https://user-images.githubusercontent.com/94364764/168426864-71f98118-c275-4078-92a4-a66fe582d0fa.png)
can anyone help me?Plz :)

**Comment by cddjr** [comment]
Because AUM is not backward compatible.
You can update AU to 2022.3.29+ or use AUM v1.1.4.

**Comment by chinabestcountry** [comment]
but there's no AUM1.1.4

**Comment by cddjr** [comment]
> but there's no AUM1.1.4

https://github.com/BitCrackers/AmongUsMenu/releases/tag/v1.1.4

**Comment by v0idp** [comment]
closed issue due to the issue being a version incompatibility
