### ISSUE TITLE
Rare crash when unhooking

### ISSUE THREAD

**Issue by kotae4** [BitCrackers/AmongUsMenu#366]
there is bug: https://github.com/BitCrackers/AmongUsMenu/blob/main/hooks/_hooks.cpp#L169
look at impl: https://github.com/BitCrackers/AmongUsMenu/blob/main/includes/detours/detours.cpp#L1937
if thread is within patched bytes when unhooking occurs then it'll crash. need to suspend every other thread and relocate instruction ptr if in trampoline.
the detours library does this but only if you call DetourUpdateThread for each other thread.

**Comment by p3tt3** [comment]
> there is bug: https://github.com/BitCrackers/AmongUsMenu/blob/main/hooks/_hooks.cpp#L169 look at impl: https://github.com/BitCrackers/AmongUsMenu/blob/main/includes/detours/detours.cpp#L1937 if thread is within patched bytes when unhooking occurs then it'll crash. need to suspend every other thread and relocate instruction ptr if in trampoline. the detours library does this but only if you call DetourUpdateThread for each other thread.

what dll injector you are using and what dll you inject AMongUsMenu..dll or version.dll?

**Comment by ChaseBrand** [comment]
Stale.
