### ISSUE TITLE
Cheat not working anymore after the new Update

### ISSUE THREAD

**Issue by Amongusce** [BitCrackers/AmongUsMenu#387]
Can you maybe try to fix that, i love your stuff. Best Regards

**Comment by Jay4rmTheBay** [comment]
Yeah damn, I noticed that too. Hope to see this up again! </3

**Comment by kotae4** [comment]
@Amongusce @Jay4rmTheBay please check closed issues and open pull requests before creating an issue.

**Comment by virtualdogs** [comment]
Use the depotdownloader to downgrade your game one update back, online functionality still works as of now & the menu works flawlessly.
