### ISSUE TITLE
getting this error when i try to compile

### ISSUE THREAD

**Issue by Pizza-Prime** [BitCrackers/AmongUsMenu#391]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(146,5): error MSB3073: The command "echo | set /p dummyName=#define GIT_CUR_COMMIT >  gitparams.h
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(146,5): error MSB3073: git rev-parse --verify HEAD >>  gitparams.h
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(146,5): error MSB3073: 
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(146,5): error MSB3073: echo | set /p dummyName=#define GIT_BRANCH >>  gitparams.h
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(146,5): error MSB3073: git rev-parse --abbrev-ref HEAD >>  gitparams.h
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(146,5): error MSB3073: :VCEnd" exited with code 128.

**Comment by v0idp** [comment]
you need to install git on your pc

**Comment by Pizza-Prime** [comment]
I do have git installed lol

**Comment by OsOmE1** [comment]
Make sure its available in your PATH.

**Comment by Pizza-Prime** [comment]
For user variables or system variables?
