### ISSUE TITLE
[GH] Upload artifacts for all jobs

### ISSUE THREAD

**Issue by 4310V343k** [BitCrackers/AmongUsMenu#392]
It would be very nice if artifacts were uploaded for all jobs, like master branch pushes or PR commits. I don't see a reason why you wouldn't do that, but it'll allow people to test (and use) new releases before they are actually released

**Comment by OsOmE1** [comment]
I'll add that yes I misunderstood you, but I stand firm as we won't do artifacts either that's just something we decided a while back. I also do not respect your attitude. I have closed this issue as I will not be acting on it please respect that.

**Comment by v0idp** [comment]
even tho the idea of artifacts isn't too bad we decided against this kinda stuff. This is purely a educational project and not meant to be used as a product. Even tho artifacts would help the end-user to test new features and patches, we don't actively support it. just to make sure: this is not a service and not meant to be tested and actively supported. thank you
