### ISSUE TITLE
The cameras on polus are broken with AUM

### ISSUE THREAD

**Issue by twitchdogo27** [BitCrackers/AmongUsMenu#402]
I've tested with and without AUM and for some reason when using AUM the cameras on polus freeze, duplicate themselves, duplicate players and backgrounds and more. if you could fix this it would be great as now I have to sit on cams and then use radar or replay to pretend I can really see what's going on

**Comment by cddjr** [comment]
I can't reproduce the issue.

**Comment by twitchdogo27** [comment]
> I can't reproduce the issue.

weird okay, ill try messing around and re installing
thx for trying!
