### ISSUE TITLE
[Feature Request] Change Kill countdown as host  before the game starts

### ISSUE THREAD

**Issue by hs233666** [BitCrackers/AmongUsMenu#406]
We know that in original game settings we can only set kill cd between "10.0 - 60.0"
But it's possible to set kill cd to 0 or some other special values as host before the game starts.
I suggest adding a special button in host tab to allow us edit the kill cd to some special values.

**Comment by hs233666** [comment]
This can be received by changing "fields._.killCooldown".
However I don't quite understand Imgui. So I'm asking for help.

**Comment by hs233666** [comment]
Well changing kill cd to 0 will cause false murder(cannot kill) , still testing other values.

**Comment by hs233666** [comment]
Simply changing fields._.killCooldown as Host isn't working.
Idk why.  =(

**Comment by imneoxyne** [comment]
Is the cheat still working?
I tried to inject the dll multiple times and nothing happens
the menu is showing up

**Comment by hs233666** [comment]
> Is the cheat still working? I tried to inject the dll multiple times and nothing happens the menu is not showing up

Its working. Check if you are playing the microsoft version. AUM does not support microsoft version.

**Comment by v0idp** [comment]
isn't possible due to the serverside checks
