### ISSUE TITLE
Getting kicked when joining a TownOfHost lobby

### ISSUE THREAD

**Issue by AAAAAXfda** [BitCrackers/AmongUsMenu#407]
I keep getting instantly kicked when trying to join a TownOfHost lobby with AUM injected, is this a bug or some sort of cheat detection?

Using AUM latest version (v1.1.26), same thing happens on both platforms, Steam & Epic Games

**Comment by AAAAAXfda** [comment]
Gif of it in action:
![Among_Us_vxbLurdYzL](https://user-images.githubusercontent.com/65740278/183264977-d931395e-a4d4-430d-86ba-874756655131.gif)

**Comment by AAAAAXfda** [comment]
I'm able to join TOH lobbies with AUM not injected, I'm assuming this is some sort of AntiCheat detection? Is there any fix for this?

**Comment by v0idp** [comment]
no support for mods
