### ISSUE TITLE
setting role as shapeshifter crashes game

### ISSUE THREAD

**Issue by Jay4rmTheBay** [BitCrackers/AmongUsMenu#411]
It seems to work the first time, but I have noticed that if I keep my impostor role as shapeshifter then by the second or third round when I start the game the screen goes black as if its gonna start but never does. I can hear people leaving the game still so its obviously still running in the background. Maybe making the roles reset back to random at the end of each match would fix this?

**Comment by Opywndow** [comment]
bad pc

**Comment by ChaseBrand** [comment]
Stale.
