### ISSUE TITLE
Injecting amongusmenu.dll with cheat engine crashes the game

### ISSUE THREAD

**Issue by Xanthus58** [BitCrackers/AmongUsMenu#412]
Hey so i'm using cheat engine as my dll injector and it worked yesterday where me and a ton of my friends wanted to use the minimap feature to enhance our game with a few other mods. Now since the new update that was released today every-time i inject the game instantly crashes. Could it be the injector I'm using or did the new update break the menu?

**Comment by ChaseBrand** [comment]
The game has updated. We'll fix it as our time allows.
