### ISSUE TITLE
Kill Time and replay of each round enhancement 

### ISSUE THREAD

**Issue by Wormix48** [BitCrackers/AmongUsMenu#415]
Stop counting seconds of a kill after reporting or pressing a button. Ability to view a replay separately for each button press or report to review the first rounds at the end of the game.

**Comment by AAAAAXfda** [comment]
Buddy, AUM doesn't count seconds of your kills or kills in general..
The second suggestion is really useful though.

**Comment by Sasha98630147** [comment]
> Дружище, AUM не считает секунды твоих убийств или убийств в целом.. Хотя второе предложение действительно полезно.

The console has a kill event that shows how many seconds ago who killed who and where. After pressing a button or report, the timer continues to run, and I would like it to stop
![image](https://user-images.githubusercontent.com/38145377/186616511-3bd2a589-903c-400f-9b90-2bb7482410d7.png)

**Comment by Sasha98630147** [comment]
We need to check in the KillEvent.cpp file whether the vote is called or not, but I don't understand the code enough to know how to do it

**Comment by OsOmE1** [comment]
> Buddy, AUM doesn't count seconds of your kills or kills in general.. The second suggestion is really useful though.

It actually does. Well, it doesn't count seconds exactly, but it records kills and their timestamps.
Sidenote, I have seen you respond to a variety of issues, and although we love the motivation. I would like to remind you that you are not a contributor, so please don't act as one. Also, make sure you do your research before making claims you clearly know nothing about.

**Comment by Sasha98630147** [comment]
As I understand it, you need to have the time of the kill count as the difference between the timestamp of the call of the meeting or report and the timestamp of the kill

**Comment by OsOmE1** [comment]
You can get rid of the timestamp by deleting [this](https://github.com/BitCrackers/AmongUsMenu/blob/e74573102c6f76202feaf8562b08c1871fae196b/events/KillEvent.cpp#L29) line

**Comment by Sasha98630147** [comment]
I don't need to remove the timestamp. I need the meeting call to show how many seconds before the meeting there was a kill

**Comment by Sasha98630147** [comment]
ReportDeadBodyEvent - KillEvent timestamps

**Comment by cddjr** [comment]
> I don't need to remove the timestamp. I need it to show how many seconds before the meeting was killed after calling the meeting

@Sasha98630147 
build&try
https://github.com/cddjr/AmongUsMenu/tree/issue_415

**Comment by Sasha98630147** [comment]
> > I don't need to remove the timestamp. I need it to show how many seconds before the meeting was killed after calling the meeting
> 
> @Sasha98630147 build&try https://github.com/cddjr/AmongUsMenu/tree/issue_415

Thank you very much, it works) The second suggestion is also interesting, if you want, you can try to implement it too)

**Comment by Sasha98630147** [comment]
![image](https://user-images.githubusercontent.com/38145377/186669400-5dfe704f-2bf3-4f2d-8f79-273d0acb4482.png)
Small bug, if there is no "clear after meeting" setting, then after the second report time of the kill changes to the new, although it should remain the same

**Comment by v0idp** [comment]
we cant give you support with forks. please post in the proper repo. closed
