### ISSUE TITLE
Reveal votes bug

### ISSUE THREAD

**Issue by Wormix48** [BitCrackers/AmongUsMenu#419]
Revealed votes are displayed twice

**Comment by Wormix48** [comment]
![image](https://user-images.githubusercontent.com/38145377/187201027-171afac9-8f0e-4c7e-b14e-34a54612d5d1.png)

**Comment by cddjr** [comment]
I think it's caused by TOH mod.

**Comment by v0idp** [comment]
closed due to game mod ( we dont support mods )
