### ISSUE TITLE
Replay Is Showing Everything 

### ISSUE THREAD

**Issue by Bj007pro** [BitCrackers/AmongUsMenu#421]
Usually the Reply wouldn't show everything that has happened in the last round all at once:
![image](https://user-images.githubusercontent.com/24400879/190730264-80af7702-84ad-4132-9610-377619aed532.png)

It also wouldn't leave a infinite trail of each player, usually the trail behind each player only last for a small length.
![image](https://user-images.githubusercontent.com/24400879/190729287-71c18263-6338-48b6-b412-82d4cbbb11f7.png)

**Comment by v0idp** [comment]
Need to implement proper timestamps for all meeting starts and ends. So we can add proper visualization

**Comment by ChaseBrand** [comment]
Stale.
