### ISSUE TITLE
I have an idea to fix this!!!

### ISSUE THREAD

**Issue by PHGaming121** [BitCrackers/AmongUsMenu#426]
On the issue #424, i asked for a fix to the move while in vent but.... i know  the anwser is no..

But i have an idea that could help with this...
Its a feature that makes the player INVISIBLE for EVERYONE... Yes, i know the anwser is no but.... it will help a lot of people!!!! I think thats a good idea...

**Comment by NickHunterD3V** [comment]
i wonder why their answer would be no, it's a cool thing

**Comment by Knoxyzz** [comment]
> 

When puttibg the "version.dll" in my among us steam folder, I get an steam error when starting the game and cant play online. Any fix?
