### ISSUE TITLE
":VCEnd”已退出，代码为 9009" How to fix it?

### ISSUE THREAD

**Issue by CryptEvc** [BitCrackers/AmongUsMenu#434]
已启动重新生成...
1>------ 已启动全部重新生成: 项目: AmongUsMenu, 配置: Debug_Version Win32 ------
1>Create gitparams.h
1>'git' 不是内部或外部命令，也不是可运行的程序
1>或批处理文件。
1>'git' 不是内部或外部命令，也不是可运行的程序
1>或批处理文件。
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: 命令“echo | set /p dummyName=#define GIT_CUR_COMMIT >  gitparams.h
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: git rev-parse --verify HEAD >>  gitparams.h
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: 
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: echo | set /p dummyName=#define GIT_BRANCH >>  gitparams.h
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: git rev-parse --abbrev-ref HEAD >>  gitparams.h
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: :VCEnd”已退出，代码为 9009。
1>已完成生成项目“AmongUsMenu.vcxproj”的操作 - 失败。
========== “全部重新生成”: 0 成功，1 失败，0已跳过 ==========

**Comment by manianac** [comment]
Duplicate issue as #433
