### ISSUE TITLE
Incompatible with Steam version 2022.10.25

### ISSUE THREAD

**Issue by RiskiTech** [BitCrackers/AmongUsMenu#437]
This appears to CTD on load on version 2022.10.25 on steam.

On a side note, how do I go about regenerating the il2cppinspector metadata on updates.

I have been messing around with trying to export the functions but I get a bloated 37MB type file.

. "C:\source\Il2CppInspector\Il2CppInspector.CLI\bin\Release\netcoreapp3.1\win-x64\publish\Il2CppInspector.exe" -i "P:\SteamLibrary\steamapps\common\Among Us\GameAssembly.dll" -m "P:\SteamLibrary\steamapps\common\Among Us\Among Us_Data\il2cpp_data\Metadata\global-metadata.dat" --cpp-out "C:\up\Desktop\au" -k -n

**Comment by v0idp** [comment]
Can't be reprocuded. Works just fine
