### ISSUE TITLE
1.1.29 Still cannot be started

### ISSUE THREAD

**Issue by CryptEvc** [BitCrackers/AmongUsMenu#440]
![2022-10-22 (7)](https://user-images.githubusercontent.com/113084046/197241471-74557662-589d-41ed-9b45-e56000975026.png)

**Comment by rskey1x1** [comment]
+
I have the same situation

**Comment by Youpromisemysonfreebobux** [comment]
that version is outdated some, you need to compile the latest

**Comment by Youpromisemysonfreebobux** [comment]
if u need, i can send a self compiled version

**Comment by rskey1x1** [comment]
> if u need, i can send a self compiled version
I would appreciate it if you send!

**Comment by Youpromisemysonfreebobux** [comment]
Alright https://github.com/Youpromisemysonfreebobux/AUMcompiled/releases/tag/AUM if you dont trust it just wait

**Comment by CryptEvc** [comment]
谢谢大家.我已经编译了

**Comment by tempotn** [comment]
> if u need, i can send a self compiled version

Can u link it to me
