### ISSUE TITLE
中文版AmongUsMenu发布 Chinese version of AmongUsMenu was released

### ISSUE THREAD

**Issue by CryptEvc** [BitCrackers/AmongUsMenu#441]
汉化by 沧神魔改, 卖钻石的小女孩, CryptEvc
Chinese by 沧神魔改, 卖钻石的小女孩l, CryptEvc
全面汉化
github链接 随缘更新
https://github.com/CryptEvc/AmongUsMenuChinese

**Comment by CryptEvc** [comment]
![1](https://user-images.githubusercontent.com/113084046/197334689-50b81904-ab84-4376-957d-aba95319e9f9.png)
![2](https://user-images.githubusercontent.com/113084046/197334690-955460e1-c9c2-414d-a15c-d4fc90dda46c.png)

**Comment by CryptEvc** [comment]
Since the original imgui does not support Chinese coding, so the translation workload is quite large

**Comment by cddjr** [comment]
imgui可以支持中文（目前AUM只加载了常用中文字符，大概有2k多个汉字吧）。 如果是硬编码写进代码中的话我记得只需要用utf8保存文件即可。

**Comment by CryptEvc** [comment]
是的，就是用的u8前缀 和 ChineseFull
