### ISSUE TITLE
[CryptEvc汉化] 更新1.20版本 中文涵盖90% AUM FOR CHINESE

### ISSUE THREAD

**Issue by CryptEvc** [BitCrackers/AmongUsMenu#453]
#441 
## 更新AUM聊天 *可进行AUM之间的通讯

- 增加AUM聊天的自定义RPC

个人持续更新,用爱发电,目前环境仅Debug可用

- ### 目前尚未汉化如下内容
1. 控制台
2. Debug菜单

- ### 下载
[Debug v1.20](https://github.com/CryptEvc/AmongUsMenuChinese/releases/tag/v1.2.0)

**Comment by v0idp** [comment]
No promotions in here
