### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Xtendera** [BitCrackers/AmongUsMenu#459]
The game on epic games crashes on whatever I do, I use debug, release, version proxy, injection (done with extreme injector on manual mapping mode). It doesn't work.
![image](https://user-images.githubusercontent.com/67883305/205425338-0599cd2c-6088-4506-849d-9ec61c465c4a.png)

**Comment by v0idp** [comment]
Did you do any modifications to the source code ? It looks like it can't find the functions which are needed for unlocking cosmetics

**Comment by Xtendera** [comment]
> Did you do any modifications to the source code ? It looks like it can't find the functions which are needed for unlocking cosmetics

Nope, just using pre built files from github.

**Comment by Glatrix** [comment]
> 

Any other mods? or mod loaders?
eg Melon Loader, Bepinex etc?
or any other mods being injected first?

**Comment by Xtendera** [comment]
> > Nope, just using pre built files from github.
> 
> Any other mods? or mod loaders? eg Melon Loader, Bepinex etc? or any other mods being injected first?

Nope, I just installed among us and injected. Letme try reinstalling

**Comment by Xtendera** [comment]
> > Nope, just using pre built files from github.
> 
> Any other mods? or mod loaders? eg Melon Loader, Bepinex etc? or any other mods being injected first?

Ok reinstalling seems to fix it. Thank you.
