### ISSUE TITLE
Windows Version not supported.

### ISSUE THREAD

**Issue by DonTry2RuN** [BitCrackers/AmongUsMenu#474]
Whenever i launch the game and the menu runs, it shows this error message
"This Version of Windows is Not Supported!"

I am currently using windows 7, does that mean Mod menu doesn't support windows 7 or is it just some kind of bug?

![image](https://user-images.githubusercontent.com/120821445/208255655-cbff8ee8-f489-410c-8453-bac5113c46c2.png)

**Comment by v0idp** [comment]
we don't support windows 7
