### ISSUE TITLE
[Bug] Setting host as any specific role causes the game to hang on start

### ISSUE THREAD

**Issue by xph11** [BitCrackers/AmongUsMenu#476]
Gets stuck on the black loading screen, usually happens after 1 or 2 games that do work.

**Comment by OsOmE1** [comment]
Can you try to recreate it using the debug version and post your logs here?

**Comment by xph11** [comment]
> Can you try to recreate it using the debug version and post your logs here?

Yeah syre, will try and report back soon :)

**Comment by xph11** [comment]
> Can you try to recreate it using the debug version and post your logs here?

[aum-log.txt](https://github.com/BitCrackers/AmongUsMenu/files/10286197/aum-log.txt)

This time it also kicked everyone on game start

**Comment by GDjkhp** [comment]
i also experienced this. i think this is both a game and aum bug conflicting each other, resulting on getting stuck and freeze on the loading screen. i think here's how to reproduce this.

set your role as "always impostor" every game. i'm seeing it to occur more on hide n seek lobbies and forcing the game to play using 3 impostors.

**Comment by xph11** [comment]
Found a weird workaround for this issue:
When you click the start button, quickly switch your roles randomly then put it back to your desired role. That should let the game start normally :)

**Comment by ChaseBrand** [comment]
Stale.
