### ISSUE TITLE
Crash on start-up after the update

### ISSUE THREAD

**Issue by GDjkhp** [BitCrackers/AmongUsMenu#477]
![image](https://user-images.githubusercontent.com/51813377/208652201-60c76cf4-e202-464b-9ac0-9012843ad8c5.png)
![image](https://user-images.githubusercontent.com/51813377/208652212-a09db0d2-28e4-4ab5-9029-352b8a7413dd.png)

Don't mind those red-lines. Idk how to reproduce but it just crashes when start-up. Occurs rarely but goes away after running the game again. Using version.dll

**Comment by OsOmE1** [comment]
If it occurs infrequently, it's probably a race condition of sorts where the GameOptionsManager has not been instantiated. Right now we wait for 3000 milliseconds we could increase it.

**Comment by v0idp** [comment]
@cddjr
