### ISSUE TITLE
forever loading screen on hide and seek

### ISSUE THREAD

**Issue by krispyking24** [BitCrackers/AmongUsMenu#482]
create a private lobby with the game mode as hide and seek in the host tab of aum set ur self to crew then in the same tab force start the game when i done these steps i got this and the game never loaded ![image](https://user-images.githubusercontent.com/77263183/209445870-944acf2b-6978-4251-bc71-9582ef4de053.png)

**Comment by hs233666** [comment]
Suggest removing host tab or role assignment in hide and seek, as you can litterly assign the imposter in game settings.

**Comment by hs233666** [comment]
Role assignment in hide and seek still needs to be improved.
