### ISSUE TITLE
FEATURE: HIDE AND SEEK MODS

### ISSUE THREAD

**Issue by PHGaming121** [BitCrackers/AmongUsMenu#485]
PLZ ADD HIDE AND SEEK MODS LIKE:
Global mods:
invisibility upgrade(can kill AND do tasks)

hide and seek mods:
set impostors number
set vents number

HOST MODS:
set kill cooldown
set custom amount of tasks ( like 20 tasks :lol:)

hope on adding this

**Comment by GDjkhp** [comment]
as void stated: we don't take any suggestions for AmongUsMenu anymore due to the inactive development. Please feel free to make any feature/bugfix PR and we will look at it, but there will be no active development or enhancements to the menu by our team anymore.

**Comment by william1east** [comment]
Set imposters number is a very troll feature and is kinda already in the menu (not for long, I hope)
(assuming you mean the number of times you can vent) You can already set maximum vent amounts in-game
What are you gonna do with a 1-second kill cooldown? make it longer?
You can already set amount of tasks in-game
