### ISSUE TITLE
menu not loading

### ISSUE THREAD

**Issue by GamebP** [BitCrackers/AmongUsMenu#486]
I don't know why it dosent show in loading game.

![image](https://user-images.githubusercontent.com/88152063/212522972-661f3fb5-e72f-4570-98f8-8a252580a2c7.png)
![image](https://user-images.githubusercontent.com/88152063/212522997-8e2c76c7-8360-4118-b5a7-e4adf0e4a726.png)

**Comment by OsOmE1** [comment]
Press delete

**Comment by GamebP** [comment]
my bad, i didnt know keybinds 👍
