### ISSUE TITLE
How can I inject on Ubuntu

### ISSUE THREAD

**Issue by Petronilus** [BitCrackers/AmongUsMenu#488]
Hello. I'm not very good with computers, I know the basics and I've only been using Linux for 1 year. To play Among Us on Linux I use Steam. As much as I put the "version.dll" file inside the game folder, the manu doesn't activate when I click on the DELETE button.

How can I open the hack in this case?

**Comment by kotae4** [comment]
We only support the Windows operating system. Feel free to add linux support and submit a PR.

**Comment by DarkReaper231** [comment]
Run the Proton version and using protontricks select version as dll override for the version.dll proxy
