### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by INVXNCXBLE** [BitCrackers/AmongUsMenu#489]
When I try to build 'AmongUsMenu.sln' as Release x86 in Microsoft Visual Studio I get an error.
![Screenshot 2023-02-03 154851](https://user-images.githubusercontent.com/124404175/216717507-c0966a5a-f3e7-4714-bc6a-5544d370356c.png)

**Comment by william1east** [comment]
Can you explain how exactly you built it?

**Comment by v0idp** [comment]
Please use the search function next time. You need git installed.
