### ISSUE TITLE
[suggestion] add control for others player chat and be able to make another player touch the button without having done so

### ISSUE THREAD

**Issue by Miguelito223** [BitCrackers/AmongUsMenu#490]
I don't know if this is the right place but I just want this suggestion because before there were more options that were later eliminated I don't know why but I would like them to come back

**Comment by william1east** [comment]
I'm unsure what your talking about, but BitCrackers have stopped developing the menu, if you want, you can do it yourself. after all, the code is open source
![image](https://user-images.githubusercontent.com/117698717/218332118-b7b65504-7933-4c67-9d27-e16d01e0591b.png)

**Comment by Miguelito223** [comment]
> I don't know if this is the right place but I just want this suggestion because before there were more options that were later eliminated I don't know why but I would like them to come back

oh I'm sorry
I don't know how to program in C+ and C anyway

**Comment by william1east** [comment]
> > I don't know if this is the right place but I just want this suggestion because before there were more options that were later eliminated I don't know why but I would like them to come back
> 
> oh I'm sorry I don't know how to program in C+ and C anyway

That's fine, there are plenty of tutorials to help you get started.

**Comment by v0idp** [comment]
closing since suggestion
