### ISSUE TITLE
Everyone becomes imp when host

### ISSUE THREAD

**Issue by NesUSA** [BitCrackers/AmongUsMenu#503]
Idk how but maybe because random rigged

**Comment by william1east** [comment]
That's really weird, could you give some insight into what you did before this happened?

**Comment by NesUSA** [comment]
i did nothin

**Comment by william1east** [comment]
wait this is in hide n seek?

**Comment by NesUSA** [comment]
not yet

**Comment by NesUSA** [comment]
well it just always sets me to imposter

**Comment by NesUSA** [comment]
well nvm
it is only buggy on classic

**Comment by Dasupergrasskakjd** [comment]
did you set 15 shapeshifters and 100%

**Comment by NSTrains** [comment]
I don't think that ignores the impostor count

**Comment by cat261326** [comment]
I know why
This is because that when you have more shapeshifters that imposters, it will actually put how many shapeshifters you have
Ex. You have 2 imposters and have it set to 5 shapeshifters, there will be 5 shapeshifters in game.

**Comment by william1east** [comment]
> I know why This is because that when you have more shapeshifters that imposters, it will actually put how many shapeshifters you have Ex. You have 2 imposters and have it set to 5 shapeshifters, there will be 5 shapeshifters in game.



> I don't think that ignores the impostor count. Whatever the impostor count is (1 - 3), they will all be impostor

😐

**Comment by nonameusers134** [comment]
Ghhhgh
