### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ashitakaa** [BitCrackers/AmongUsMenu#504]
crashes after i vote, using the version.dll one

**Comment by william1east** [comment]
You are on an old version of AUM

**Comment by Ashitakaa** [comment]
> 

i just downloaded the release, cant be cause of version, cant it be that im not using original paid version of among us?

**Comment by william1east** [comment]
Are you saying you pirated it? If so.
![image](https://user-images.githubusercontent.com/117698717/222810789-f0ae9055-8721-41bb-a414-e91d8578b20a.png)

**Comment by Ashitakaa** [comment]
oh damn, thank you, do you know about sum menu that i can use on cracked version

**Comment by william1east** [comment]
Buy the game, its like, 3$ or something

**Comment by thegoat200l** [comment]
how do you get the updated version?

**Comment by v0idp** [comment]
Closed due to piracy talk.
