### ISSUE TITLE
New function

### ISSUE THREAD

**Issue by Dasupergrasskakjd** [BitCrackers/AmongUsMenu#506]
Would you be able to create a function that spams report?

**Comment by william1east** [comment]
Hate to break it to you, but...

![image](https://user-images.githubusercontent.com/117698717/226205194-9cad5261-5410-4e7c-92e6-867b3697fb78.png)

![image](https://user-images.githubusercontent.com/117698717/226205283-8f147fc4-badc-4256-b1b3-ac67026455e2.png)
