### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by Dasupergrasskakjd** [BitCrackers/AmongUsMenu#507]
Error The BaseOutputPath/OutputPath property is not set for project 'AmongUsMenu.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release_Version'  Platform='Win32'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.	AmongUsMenu	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	832

**Comment by Dasupergrasskakjd** [comment]
that's what i did

**Comment by v0idp** [comment]
I can't seem to reproduce the issue. can you provide a step by step guide what you did ?!

**Comment by Dasupergrasskakjd** [comment]
1.I opened the sln file in VS
2.I pressed Ctrl+Shift+B
3.it says build failed

**Comment by v0idp** [comment]
I tried again and I can't reproduce it, do you have Desktop development for C++ installed ? 
![image](https://user-images.githubusercontent.com/39016303/226755208-a7450d7e-b20b-4909-8e07-113d8a7c8d88.png)

**Comment by Dasupergrasskakjd** [comment]
I'm not sure, where can I check?

**Comment by v0idp** [comment]
Type "Visual Studio Installer" into your Windows Start and open it. there you can modify your VS Installation

**Comment by Dasupergrasskakjd** [comment]
Oh I doesn't, I will try to build it after it is installed

**Comment by Dasupergrasskakjd** [comment]
It builded successfully, thank you
