### ISSUE TITLE
Crash after the end of voting

### ISSUE THREAD

**Issue by elpmoraes** [BitCrackers/AmongUsMenu#508]
hey guys, in AUM, after the vote session, the game crashs:
Exception thrown at 0x5F687CFC (UnityPlayer.dll) in Among Us.exe: 0xC0000005: Access violation while reading location 0x0000000C.
Unhandled exception at 0x5F687CFC (UnityPlayer.dll) in Among Us.exe: 0xC0000005: Access violation while reading location 0x0000000C.

**Comment by v0idp** [comment]
please update to latest AUM, read #faq in discord and next time properly post your logs.
