### ISSUE TITLE
Unable to display properly after changing Chinese

### ISSUE THREAD

**Issue by huolangwangluo** [BitCrackers/AmongUsMenu#517]
![IMG_20230430_113850](https://user-images.githubusercontent.com/107757948/235334391-c15e7261-1085-4207-b6ed-8479d7bda1bd.jpg)
![IMG_20230430_113903](https://user-images.githubusercontent.com/107757948/235334392-c27be15b-c256-4003-81b6-32474e0a7c85.jpg)

**Comment by XiezibanWrite** [comment]
要不 你换个编码？或许是不支持？

**Comment by cddjr** [comment]
确保cpp文件采用的是UTF8编码，另外就是imgui的字库最好加载完整版的（目前AUM只加载了常用汉字）

**Comment by huolangwangluo** [comment]
> 确保cpp文件采用的是UTF8编码，另外就是imgui的字库最好加载完整版的（目前AUM只加载了常用汉字）

完整版的怎么加载
编码在visual改了UTF-8

**Comment by huolangwangluo** [comment]
> 要不 你换个编码？或许是不支持？

我发过怎么改中文作者回复自己改 应该是支持

**Comment by XiezibanWrite** [comment]
> 确保cpp文件采用的是UTF8编码，另外就是imgui的字库最好加载完整版的（目前AUM只加载了常用汉字）

对了我也想问下 话说你的那个AUM是停更了吗？之前看到你的AUM似乎是要兼容TOH TOHR TOHY和TOR的

**Comment by cddjr** [comment]
> > 确保cpp文件采用的是UTF8编码，另外就是imgui的字库最好加载完整版的（目前AUM只加载了常用汉字）
> 
> 对了我也想问下 话说你的那个AUM是停更了吗？之前看到你的AUM似乎是要兼容TOH TOHR TOHY和TOR的

因为那些模组的更新并没有考虑向下兼容，这意味着他们更新后我这边适配的话也得大改动，精力有限，等我啥时候又想玩AU的时候再更了。主要就是揭露职业这些，更新倒也简单，同步职业id的定义即可。

**Comment by william1east** [comment]
> > 要不 你换个编码？ 或许是不支持？
> 
> 我发过怎么改中文作者回复自己改 应该是支持

我之前已经说过了，你可以自己完成这个，如果你还不想的话，我可能会为中文创建一个派生版本，毕竟我现在也没有什么项目要做。

**Comment by huolangwangluo** [comment]
> > > 要不 你换个编码？ 或许是不支持？
> > 
> > 
> > 我发过怎么改中文作者回复自己改 应该是支持
> 
> 我之前已经说过了，你可以自己完成这个，如果你还不想的话，我可能会为中文创建一个派生版本，毕竟我现在也没有什么项目要做。

那是我不想吗 是不会 现在就差中文显示不正常了

**Comment by Lukim99** [comment]
You need to modify the imgui_draw.cpp code. ImGui does not natively support Unicode.
