### ISSUE TITLE
cant inject dll

### ISSUE THREAD

**Issue by Zaidbaidadekalb** [BitCrackers/AmongUsMenu#522]
Every time i try to  inject the dll nothing would happen.

**Comment by william1east** [comment]
Have you tried to...
Press the delete key?
Use a different injector?
Redownload [AUM?](https://github.com/BitCrackers/AmongUsMenu/releases/tag/v1.2.8)
Or use [AUM launcher?](https://github.com/BitCrackers/aum-launcher)
If not, do so and see if it fixes your problem, if it doesn't you can place your AUM log here **(It should be in your games directory)**
