### ISSUE TITLE
Crash when meeting ends

### ISSUE THREAD

**Issue by NotToufG** [BitCrackers/AmongUsMenu#527]

**Comment by william1east** [comment]
You probably have an outdated version of AUM. [Try redownloading AUM](https://github.com/BitCrackers/AmongUsMenu/releases/tag/v1.2.8)

**Comment by NotToufG** [comment]
thanks

**Comment by william1east** [comment]
Its on the download page?

**Comment by Bylander10** [comment]
yeah, the game crashes after a while, i just downloaded latest version and it's not working

**Comment by william1east** [comment]
> yeah, the game crashes after a while, i just downloaded latest version and it's not working

That's a known issue
since AUM hasn't been updated to add these bugfixes and the main team killed support for it your going to be experiencing issues like that for however long AUM is updated by the community

**Comment by Bylander10** [comment]
Appparently verifying the games files in epic games fixes the crashing error(?) dunno if it's gonna happen again but no more crashes for me

**Comment by NotToufG** [comment]
thanks
