### ISSUE TITLE
syntax error: unexpected token ')', expected 'expression'

### ISSUE THREAD

**Issue by Murat127121** [BitCrackers/AmongUsMenu#528]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2760	syntax error: unexpected token ')', expected 'expression'	AmongUsMenu	C:\Users\XXXXXX\Desktop\AmongUsMenu-main\AmongUsMenu\framework\il2cpp-helpers.h	38	

error when building

**Comment by kotae4** [comment]
https://github.com/BitCrackers/AmongUsMenu/actions/runs/4547751505/jobs/8018019087#step:3:249

PEBKAC

**Comment by Murat127121** [comment]
well its not working fine for me can you maybe help me fix it kotae4

**Comment by Murat127121** [comment]
please bro im new to coding idk what to do

**Comment by Murat127121** [comment]
@kotae4
