### ISSUE TITLE
How to update structs in il2cpp-types.h?

### ISSUE THREAD

**Issue by TimShaw1** [BitCrackers/AmongUsMenu#531]
I have tried using il2cppinspector to update il2cpp-types.h, however the generated file is far larger than the one included here (over 1 million lines). @cddjr how do you set this up to update the structs when needed? I ask as I am using a modified version of this project alongside a project of my own. If the game updates and the structs change, I'd like to be able to update the structs myself.

**Comment by Dasupergrasskakjd** [comment]
Browse used_types.txt and add used types to il2cpp-types.h with your ide
