### ISSUE TITLE
game crashes after joining the game

### ISSUE THREAD

**Issue by mallone11** [BitCrackers/AmongUsMenu#534]
i use process hacker as an injector

it doesnt matter if I inject after the start or before, the game will still crash. in general, we are waiting for a new dll, pls make a patch faster

**Comment by trololoxd** [comment]
Its because of the new version, Youll have to edit it to fix it.

**Comment by felpfcw** [comment]
How do i edit it?

**Comment by felpfcw** [comment]
can someone send a tutorial how to edit?

**Comment by william1east** [comment]
> can someone send a tutorial how to edit?

Figure it out, it's not that easy.

**Comment by felpfcw** [comment]
:((
