### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Byelzinho** [BitCrackers/AmongUsMenu#540]
Pls, do a tutorial..

**Comment by william1east** [comment]
Trust me, I would be **VERY** glad to make a tutorial on how to use AUM if anyone would watch the damn thing.

**Comment by Byelzinho** [comment]
I waiting you create that shit, where is

Em ter., 20 de jun. de 2023 às 4:04 PM, OsOmE1 ***@***.***>
escreveu:

**Comment by Byelzinho** [comment]
You poor, shhhh bitch

Em qua., 21 de jun. de 2023 às 12:35 PM, JohnathanHenry <
***@***.***> escreveu:

**Comment by JohnathanHenry** [comment]
Mother fucker son of a bitch

**Comment by JohnathanHenry** [comment]
Go fuck yourself @Byelzinho

**Comment by Byelzinho** [comment]
Your mother shit on you when you born

Em qua., 21 de jun. de 2023 às 12:36 PM, JohnathanHenry <
***@***.***> escreveu:

**Comment by JohnathanHenry** [comment]
Shut up you fucking asshole. Nobody loves you.

**Comment by JohnathanHenry** [comment]
You're fucking fatherless @Byelzinho

**Comment by Byelzinho** [comment]
You are a coal cub, your mother is a transvestite

Em qua., 21 de jun. de 2023 às 12:39 PM, yug boy ***@***.***>
escreveu:

**Comment by JohnathanHenry** [comment]
Your moms a fucking slag

**Comment by Byelzinho** [comment]
My mother tried to abort me, but today I give children to mothers like
yours my son 😂😂😂😂😂

Em qua., 21 de jun. de 2023 às 12:40 PM, JohnathanHenry <
***@***.***> escreveu:
