### ISSUE TITLE
Assertion error during debug

### ISSUE THREAD

**Issue by Dasupergrasskakjd** [BitCrackers/AmongUsMenu#548]
![image](https://github.com/BitCrackers/AmongUsMenu/assets/106623583/081b5a2f-c370-41d0-a80c-d25395ae5c12)
The assertion error happened randomly, but first was when a game ends and I leave, second was when i click "online" at the page

**Comment by Dasupergrasskakjd** [comment]
I tried to reproduced it and I can't

**Comment by cddjr** [comment]
What version of aum are you using?

**Comment by Dasupergrasskakjd** [comment]
The newest version
It seems to be something about keybinds, it only happens when i press fn+arrow
