### ISSUE TITLE
Browser thinks this is a virus.

### ISSUE THREAD

**Issue by cat261326** [BitCrackers/AmongUsMenu#558]
I have 2 browsers, I have tried both of them and each one thinks that the .zip is a virus. Neither one of them tells me what is blocking it.

**Comment by william1east** [comment]
Well, yeah, the DLL is made to modify memory for Among Us. Which is common virus behavior.
The project is open source and built by GitHub so you can view the code and confirm if it is or isn't a virus.
If you want to download it anyway there should be a way to disable your browsers anti-virus, but that's up to you.
