### ISSUE TITLE
2023 7 11e AUM IS LOST

### ISSUE THREAD

**Issue by sungbly1tsstt** [BitCrackers/AmongUsMenu#565]

**Comment by sungbly1tsstt** [comment]
![图片](https://github.com/BitCrackers/AmongUsMenu/assets/114800438/c7c9fe48-1829-45aa-bd16-1826760abdb9)

**Comment by burrumiau** [comment]
how you manage to download it?

**Comment by sungbly1tsstt** [comment]
V1.2.9

**Comment by sungbly1tsstt** [comment]
epic amongus version
github download

**Comment by sungbly1tsstt** [comment]
![图片](https://github.com/BitCrackers/AmongUsMenu/assets/114800438/f0ca42b1-9bc5-4530-b478-eebc1b4a7f67)
