### ISSUE TITLE
Menu not opening with most recent ver

### ISSUE THREAD

**Issue by zzlyz** [BitCrackers/AmongUsMenu#571]
menu wasnt showing when press del so i downloaded debug ver and it says this:

> Unable to locate ChatController_AddChat
> [16:20:55][DEBUG - AUM - cctor_finished] Class AmongUsClient Has Static Constructor: false
> [16:20:55][DEBUG - AUM - Run] Game::pAmongUsClient is 0x1ADD0E18 -> 0x1A957B60
> [16:20:55][DEBUG - AUM - cctor_finished] Class GameData Has Static Constructor: true
> [16:20:55][DEBUG - AUM - Run] Game::pGameData is 0x1ADD0FA8 -> 0x00000000
> [16:20:55][DEBUG - AUM - cctor_finished] Class PlayerControl Has Static Constructor: true
> [16:20:55][DEBUG - AUM - Run] Game::pAllPlayerControls is 0x1ADD0FEC -> 0x1D5C5E20
> [16:20:55][DEBUG - AUM - cctor_finished] Class PlayerControl Has Static Constructor: true
> [16:20:55][DEBUG - AUM - Run] Game::pLocalPlayer is 0x1ADD0FE8 -> 0x00000000
> [16:20:55][DEBUG - AUM - cctor_finished] Class ShipStatus Has Static Constructor: false
> [16:20:55][DEBUG - AUM - Run] Game::pShipStatus is 0x190385F8 -> 0x00000000
> [16:20:55][DEBUG - AUM - cctor_finished] Class LobbyBehaviour Has Static Constructor: false
> [16:20:55][DEBUG - AUM - Run] Game::pLobbyBehaviour is 0x19038600 -> 0x00000000
> [16:20:55][DEBUG - AUM - Run] Game::RoleManager is 0x21bc2618
> Failed to hook ChatController_AddChat, error 6

**Comment by stretch07** [comment]
yep, same here. @cddjr any fix ?

**Comment by cddjr** [comment]
au version? menu version?
