### ISSUE TITLE
Can't inject into among us

### ISSUE THREAD

**Issue by oIKR2** [BitCrackers/AmongUsMenu#575]
My among us is built in 64 bits (Aka XBox among us) and it says the dll is 32 bits so I can't inject it :(. Is there a 64 bit version? I know the steam one is 32 bits, but I can't buy it from steam, I already have it in Xbox store, pc.

**Comment by JakeHumter** [comment]
@oIKR2 
Private message me on discord JakeGames1013 ill tell you something

**Comment by OsOmE1** [comment]
Sorry we do not support 64-bit

**Comment by JakeHumter** [comment]
i was gonna send him a link for among us on itch lol

**Comment by JakeHumter** [comment]
sorry lol
