### ISSUE TITLE
Fail creating font when injecting AUM in proton

### ISSUE THREAD

**Issue by RackYican** [BitCrackers/AmongUsMenu#591]
When injecting AUM to game appears this:
![Screenshot_20230926_124220](https://github.com/BitCrackers/AmongUsMenu/assets/125700377/fa5ef41f-5fe7-4427-817b-e22d93c35c12)
I have all fonts installed, debug mode - console in AUM launcher closes after closing Among Us.

**Comment by OsOmE1** [comment]
proton is not supported

**Comment by SolsticeSpectrum** [comment]
Doesn't happen to me, are you sure you are running Among Us under Steam's proton and not lutris or other game launcher?
