### ISSUE TITLE
Chat spam feature

### ISSUE THREAD

**Issue by stretch07** [BitCrackers/AmongUsMenu#600]
Hi
Among us places several restrictions on their chat such as not sending links, not spamming, not adding one of the special characters, etc
Most if not all of these are just client-side restrictions.
Would it be possible for you guys to add a chat spam feature?
BTW - AMong us uses this rich text system internally - http://digitalnativestudios.com/textmeshpro/docs/rich-text/ - hopefully that would also be possible
Lastly, the game has been updated to a new version with a new map. I don't think the menu is working since then

@v0idp @NikoCat233 @manianac

**Comment by OsOmE1** [comment]
no

**Comment by OsOmE1** [comment]
> This project is no longer in active development by the BitCrackers team. Therefore all issues created will be ignored or closed.
https://github.com/BitCrackers/AmongUsMenu#no-active-development

Read.
