### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Bigouf** [BitCrackers/AmongUsMenu#607]
Issue

**Comment by felix-yata** [comment]
its not a place to ask questions like this

**Comment by Lukim99** [comment]
When you are the host, AUM run code that determines the players' roles. This takes precedence over Among Us, so if you want to target someone in particular as the tagger, set that player as an imposter in the Host tab.

**Comment by Bigouf** [comment]
The result by doing that was two impostors lol
