### ISSUE TITLE
AmongUsMenu 

### ISSUE THREAD

**Issue by Mommy288** [BitCrackers/AmongUsMenu#608]
Sabotage does not work in hide-and-seek mode

**Comment by GDjkhp** [comment]
that's how hide and seek works

**Comment by Mommy288** [comment]
@GDjkhp So it's not a mistake?

**Comment by Lukim99** [comment]
This is an intentional design. Sabotage cannot be activated in hide and seek mode.
If you try to use sabotage in hide and seek mode, a crash will occur.
If you want to test it, modify the code yourself.
