### ISSUE TITLE
Skins and caught

### ISSUE THREAD

**Issue by FearRizzy** [BitCrackers/AmongUsMenu#611]
I only wanna use the menu for skins so im not sure if possible to have all the skins without being able to use the menu. My second question is someone said I was using it from a website they checked so I wanna know how to make it impossible for people to tell I am using or have used it. I didn't even use the menu at all during the game btw. I also use the menu by just dropping the 3 files into the base game directory if that matters at all.

**Comment by Lukim99** [comment]
If you don't touch anything in the menu, no one will know you're using it.
The unlocked costume feature does not require separate activation and is automatically activated when AUM is applied.

You can hide it more completely by removing code from HandleRPC that transmits information to other AUM users.

**Comment by FearRizzy** [comment]
When I boot the game the menu pops up but if I just close it without touching any tabs I should be good then? Also how do I remove the code from HandleRPC I'm not sure what that is

**Comment by Lukim99** [comment]
I don't know what exactly you're worried about.
forget about HandleRPC.
just close the menu tab.

**Comment by GDjkhp** [comment]
use this instead:
https://www.unknowncheats.me/forum/among-us/521567-amonguscosmetics.html

**Comment by FearRizzy** [comment]
> I don't know what exactly you're worried about. forget about HandleRPC. just close the menu tab.

i play in a discord server and can get banned for it so if people are catching me using the menu thats the issue haha but i appreciate it

**Comment by FearRizzy** [comment]
> use this instead: https://www.unknowncheats.me/forum/among-us/521567-amonguscosmetics.html

dude yes this is exactly what i wanted
