### ISSUE TITLE
Fix bug in hide n seek mode

### ISSUE THREAD

**Issue by survival235** [BitCrackers/AmongUsMenu#612]
I found a bug in the hide n seek mode for Among Us. The normal game settings are not disabled in this mode, which causes several problems. For example, crewmates can get special roles like scientist, engineer, guardian angel, etc. that are not supposed to be in hide n seek mode. They also don’t get the default vent option that is only for hide n seek mode. If the host make the lobby private and set who they want to be the impostor in the game, they don’t become the impostor, even though it is also set in the mod. And if they do become the impostor, then there are two impostors in the game instead of one, which ruins the hide n seek experience. This bug was supposed to be fixed by a commit #592  in the release, but it is still happening.

**Comment by OsOmE1** [comment]
> This project is no longer in active development by the BitCrackers team. Therefore all issues created will be ignored or closed.
