### ISSUE TITLE
Update to v2023.11.28

### ISSUE THREAD

**Issue by lucas119** [BitCrackers/AmongUsMenu#614]
Thank you for updating 2023.10.24! Could you update v2023.11.28? a New Cosmicube has been added (Indie Cosmicube)

Thank you!

**Comment by AndrewS100000** [comment]
Yes I'm updating it right now

**Comment by TXxKo** [comment]
Legend for updating it, if you don't mind me asking how long will this take? No rush just wondering.

**Comment by Lukim99** [comment]
> Legend for updating it, if you don't mind me asking how long will this take? No rush just wondering.

Just use it. No need to update.

**Comment by felix-yata** [comment]
> Legend for updating it, if you don't mind me asking how long will this take? No rush just wondering.

The update for the last time got about 5 days, 24-29=5, if he just started updating it, ti would be ready by 7-8 december

**Comment by cddjr** [comment]
> > Legend for updating it, if you don't mind me asking how long will this take? No rush just wondering.
> 
> 
> 
> The update for the last time got about 5 days, 24-29=5, if he just started updating it, ti would be ready by 7-8 december

Good point 🙂

**Comment by DarkPenguin24** [comment]
> When will the **AUM** be updated with new functions like viewing role settings if you are not the host, cheating if you are not the host, banning and kicking if you are not the host (for example, some kind of ping error), cards that are unlocked on the first of April, like a mirror skeld, pass voting (like on phone cheats) the end of the game is the same as on phone cheats. Of course, I understand that it’s difficult, but at least something that I’ve listed will happen?

This project is no longer in active development by the BitCrackers team. Therefore implement it yourself.
