### ISSUE TITLE
Add door closes/opens to console during hide and seek

### ISSUE THREAD

**Issue by fillwithjoy1** [BitCrackers/AmongUsMenu#615]
Hello!
This is an amazing project!
I'm wondering if it is even possible to find who closes doors on hide n seek (if possible at all, other hacks are able to close doors on hide and seek),
Thanks!

**Comment by fillwithjoy1** [comment]
excuse me how is this completed?

**Comment by OsOmE1** [comment]
> This project is no longer in active development by the BitCrackers team. Therefore all issues created will be ignored or closed.
