### ISSUE TITLE
How do you make yourself invisible to other aum users?

### ISSUE THREAD

**Issue by FearRizzy** [BitCrackers/AmongUsMenu#617]

**Comment by william1east** [comment]
Short Answer: Do it yourself

Long Answer: There is a specific packet that is sent to other users that is used to say "This person is using AUM", If you really cared about not getting caught then you would look in the source code, find that packet, and stop it from being sent. No one will tell you which packet it is, you have to figure it out yourself.

[Source](https://i.imgur.com/C4bfSUt.png)

**Comment by FearRizzy** [comment]
thank you and I think I understand. would u mind explaining how you would stop it from sending
