### ISSUE TITLE
Idea: Task Bot

### ISSUE THREAD

**Issue by pixo2000** [BitCrackers/AmongUsMenu#634]
A Bot that does the Task fast and maybe also a bot thats walking to the tasks

**Comment by J4YD3NLUL** [comment]
so, just a navbot?

**Comment by pixo2000** [comment]
yeah:
1st Option: A Bot that automaticly does the Task when the User opens a Task window(But not just sends the packets. It should realy do it)
2nd Option: A Bot that walks around to the different Tasks
3rd Option: A Full Autoplay Bot, Running around, Doing Tasks and when a Meeting is running it can vote the Imposter or Skip and send in chat what he was doing/if it saw a kill or vent

**Comment by manianac** [comment]
AUM is no longer supported.  I recommend forking it and working on the bot.
