### ISSUE TITLE
How to remove "is Using AUM"?

### ISSUE THREAD

**Issue by lyy2182** [BitCrackers/AmongUsMenu#637]
I want to remove this feature so that other AUM users don't know I'm using AUM.
I found a container: "State.aumUsers" and knew that aum would add my own playerid to the container, but I don't know how this container was sent to other AUM users.
Where is the code that sends the container to other AUM users?

**Comment by OsOmE1** [comment]
It was added three years ago. Also, we are not going to give you instructions on how to remove it. I suggest you try to figure it out yourself, the code base is not that large. I will leave you with a hint: "want to make other AUM users blind, a funny number you should find".

**Comment by lyy2182** [comment]
@OsOmE1 First, thank you for your help, and second, I changed "if (State.rpcCooldown == 15) {" from line 43 of PlayerControl.cpp to "if (State.rpcCooldown == 17) {" so that the statement that sent the rpc message could never be executed. Is this that "funny number" you are talking about? It worked successfully. Other AUM users can't see that I'm using AUM but I can't see if anyone else is using AUM either. Can it be changed to I can see others and others can't see me? Can you give me more tips?
