### ISSUE TITLE
Need to Add 3 new roles.

### ISSUE THREAD

**Issue by lucas119** [BitCrackers/AmongUsMenu#643]
Hi! Thanks for Updating the Game and it somehow made my Game Work! So apparently I need your help to add 3 new roles yet, while my Game that I host doesn't work too well, it has Missing 3 New Roles such as Tracker, Noisemaker and Phantom.

Could you please fix it ASAP? thanks!

-Lucas

**Comment by lephiz69** [comment]
You can use the Sickomenu fork of AUM, https://github.com/g0aty/SickoMenu
